"""Cem perguntas estratégicas sobre o Jev: o que decidir, e o que decide.

A diferença para as cem hipóteses é de propósito. Aquelas perguntavam **o que o modelo faz**, e a
resposta era sustentada ou falsificada. Estas perguntam **o que fazer com ele**, e a resposta é
uma decisão com um número atrás. Uma pergunta estratégica que não muda nenhuma decisão não é
estratégica: é curiosidade cara.

Por isso cada pergunta declara quatro coisas:

  `pergunta`  o que se quer saber, em linguagem de quem decide;
  `decisao`   qual decisão concreta ela informa — se não houver, a pergunta não entra;
  `fonte`     de onde sai a resposta: `dado` (o que já foi medido), `conta` (aritmética sobre o
              medido, com os parâmetros declarados) ou `medicao` (coleta nova);
  `vira_se`   o que teria de ser verdade para a decisão mudar. É o análogo do critério de
              falsificação, e serve à mesma função: impedir resposta que serve para tudo.

As perguntas de fonte `conta` carregam parâmetros que **não são medidos** — preço de um modelo
caro, custo-hora de revisão, volume mensal. Esses parâmetros estão declarados na resposta, um a
um, e a resposta diz como ela muda se o parâmetro mudar. Conta com parâmetro escondido é opinião
com aparência de número.
"""

from __future__ import annotations

FAMILIAS = {
    'A': 'A decisão de adotar',
    'B': 'Unidade econômica',
    'C': 'Desenho da política de uso',
    'D': 'Risco e custo do erro',
    'E': 'Segurança e adversário',
    'F': 'Escopo: onde vale e onde não',
    'G': 'As alternativas',
    'H': 'Operação e manutenção',
    'I': 'Governança e prova',
    'J': 'Os próximos movimentos',
}

FONTES = {
    'dado': 'responde com o que já foi medido',
    'conta': 'aritmética sobre o medido, com parâmetros declarados',
    'medicao': 'exigiu coleta nova',
}


def Q(numero, familia, pergunta, decisao, fonte, vira_se):
    return {'id': f'Q{numero:03d}', 'familia': familia, 'pergunta': pergunta,
            'decisao': decisao, 'fonte': fonte, 'vira_se': vira_se}


PERGUNTAS = [
    # ------------------------------------------------------------- A · adotar
    Q(1, 'A', 'Em qual aplicação o ganho sobre o método atual é maior?',
      'por onde começar a integração',
      'dado', 'outra aplicação mostrar ganho maior sobre a linha de base dela'),
    Q(2, 'A', 'Qual aplicação oferece o melhor ganho por unidade de risco assumido?',
      'por onde começar, considerando o que quebra se der errado',
      'dado', 'a aplicação de menor risco deixar de ter ganho medido'),
    Q(3, 'A', 'Existe aplicação em que o método atual já basta?',
      'onde NÃO gastar esforço de integração',
      'dado', 'a diferença contra a linha de base cair abaixo de 5 pontos'),
    Q(4, 'A', 'A vantagem sobre o LLM barato sobrevive ao critério de um anotador independente?',
      'se a escolha do modelo precisa de justificativa além de preço',
      'dado', 'aparecer vantagem significativa sob o critério independente'),
    Q(5, 'A', 'Qual o volume mensal mínimo em que o custo de integrar se paga?',
      'se vale integrar ou rodar na mão',
      'conta', 'o custo de integração declarado mudar de ordem de grandeza'),
    Q(6, 'A', 'Adotar obriga a redesenhar a taxonomia que já existe?',
      'quanto trabalho de modelagem entra no projeto',
      'dado', 'o número de classes do domínio passar do limite medido sem custo'),
    Q(7, 'A', 'Quantas classes o domínio pode ter sem custo de acurácia?',
      'quão fina a taxonomia pode ser',
      'dado', 'a acurácia cair mais de 3 pontos dentro do limite hoje declarado'),
    Q(8, 'A', 'A adoção exige dado rotulado antes de começar?',
      'se existe dependência de trabalho humano prévio',
      'dado', 'o desempenho sem ajuste cair abaixo do aceitável do caso de uso'),
    Q(9, 'A', 'Quanto tempo até o primeiro resultado utilizável?',
      'o formato do piloto',
      'conta', 'a geração de corpus deixar de ser automatizável'),
    Q(10, 'A', 'Se só um projeto puder ser feito este trimestre, qual é?',
      'a alocação de esforço',
      'dado', 'a aplicação escolhida perder economia medida ou ganhar risco novo'),

    # ------------------------------------------------------------- B · unidade econômica
    Q(11, 'B', 'Quanto custa mil decisões, medido e não estimado?',
      'a linha do orçamento',
      'dado', 'o preço do provedor mudar'),
    Q(12, 'B', 'A seleção de contexto se paga quando se conta a chamada de ordenação?',
      'se a Aplicação 3 é economia real ou contábil',
      'conta', 'o preço do modelo caro ficar abaixo do ponto de equilíbrio calculado'),
    Q(13, 'B', 'Qual a razão mínima de preço entre o modelo caro e o Jev para a seleção valer?',
      'em quais pilhas a seleção faz sentido',
      'conta', 'a razão de preço do seu caso ficar abaixo da calculada'),
    Q(14, 'B', 'A partir de quantos candidatos a ordenação custa mais do que carregar tudo?',
      'o tamanho máximo do conjunto de candidatos',
      'conta', 'o número de candidatos do seu caso passar do limite'),
    Q(15, 'B', 'O k adaptativo economiza o bastante para justificar a complexidade?',
      'se implementar a política de k variável',
      'dado', 'a economia adicional sobre k fixo passar de 10 pontos em corpus difícil'),
    Q(16, 'B', 'Quanto se economiza, em dólares, por mil perguntas no arranjo recomendado?',
      'o número que vai para a justificativa de projeto',
      'conta', 'o preço do modelo respondedor mudar'),
    Q(17, 'B', 'Que fração do orçamento do estudo virou chamada inútil?',
      'quanto reservar de folga no próximo programa',
      'dado', 'a taxa de falha do provedor subir'),
    Q(18, 'B', 'O custo por decisão cresce com o texto de um jeito que quebre a conta?',
      'se há limite de tamanho a impor na entrada',
      'dado', 'a relação custo-tamanho deixar de ser aproximadamente linear'),
    Q(19, 'B', 'Votar em três chamadas triplica o custo — isso cabe no custo por decisão?',
      'se a política de votação é viável para a classe irreversível',
      'conta', 'o custo por decisão passar a ser material contra o custo do erro'),
    Q(20, 'B', 'Quanto custa rodar a suíte de canários todo dia por um ano?',
      'se o monitoramento contínuo entra no orçamento',
      'conta', 'o custo anual passar de 1% do teto autorizado'),

    # ------------------------------------------------------------- C · política
    Q(21, 'C', 'Qual corte de confiança entrega a maior cobertura com zero erro aceito?',
      'o corte a configurar em produção',
      'dado', 'aparecer erro acima do corte escolhido no conjunto inteiro'),
    Q(22, 'C', 'Como é a curva risco-cobertura, e onde está o joelho?',
      'a política de automação parcial',
      'dado', 'a curva mudar de forma no seu material'),
    Q(23, 'C', 'O corte de 0,99 recomendado no guia sobrevive ao conjunto inteiro de decisões?',
      'manter ou mudar a recomendação publicada',
      'dado', 'a taxa de erro acima de 0,99 passar de 1%'),
    Q(24, 'C', 'Qual k recomendar, considerando acerto e custo juntos?',
      'o parâmetro padrão da Aplicação 3',
      'dado', 'k = 2 superar k = 1 com significância'),
    Q(25, 'C', 'A classe de escape deve ser obrigatória em toda taxonomia?',
      'o padrão de desenho de taxonomia',
      'dado', 'aparecer caso em que a classe de escape piora a decisão'),
    Q(26, 'C', 'A instrução de sujeito deve ser padrão em toda classificação de pedido?',
      'o texto padrão da instrução',
      'dado', 'a instrução de sujeito piorar alguma família'),
    Q(27, 'C', 'Sob que condição vale decompor a decisão em várias perguntas?',
      'quando usar múltiplas perguntas no mesmo payload',
      'dado', 'a pergunta auxiliar passar a ser mais confiável que a decisão'),
    Q(28, 'C', 'Mandar de oito em oito é seguro? Para quais classes?',
      'se usar lote para baratear',
      'dado', 'o efeito de posição voltar a aparecer com significância'),
    Q(29, 'C', 'Quantas repetições para decisão sem volta?',
      'a política de repetição na classe irreversível',
      'dado', 'a taxa de oscilação medida subir'),
    Q(30, 'C', 'A política recomendada muda se o canal tiver outra mistura de assuntos?',
      'se a configuração precisa ser por canal',
      'dado', 'a variação entre misturas passar de 5 pontos'),

    # ------------------------------------------------------------- D · risco
    Q(31, 'D', 'Qual a taxa medida de erro grave, e qual o teto estatístico dela?',
      'se a classe irreversível pode ser automatizada',
      'dado', 'o teto do intervalo cair abaixo do risco tolerado'),
    Q(32, 'D', 'Quanto custa um erro grave comparado ao custo da decisão?',
      'quanto vale gastar em salvaguarda',
      'conta', 'o custo declarado do erro mudar de ordem de grandeza'),
    Q(33, 'D', 'Qual a exposição esperada por mil decisões no corte recomendado?',
      'o número que entra na avaliação de risco',
      'conta', 'a taxa de erro acima do corte mudar'),
    Q(34, 'D', 'Qual família de erro é a mais cara?',
      'onde pôr revisão humana',
      'dado', 'outra família passar a concentrar o erro'),
    Q(35, 'D', 'O erro se concentra em alguma classe?',
      'se a revisão pode ser seletiva por classe',
      'dado', 'a concentração deixar de existir'),
    Q(36, 'D', 'Existe modo de falha em que a confiança não avisa?',
      'se o corte basta como salvaguarda',
      'dado', 'nenhum modo silencioso restar'),
    Q(37, 'D', 'A taxa de não-resposta cria risco operacional?',
      'se é preciso caminho de contingência',
      'dado', 'a taxa passar de 2%'),
    Q(38, 'D', 'Qual o pior caso de acurácia medido em condição plausível de produção?',
      'o pior cenário a declarar',
      'dado', 'aparecer condição plausível pior'),
    Q(39, 'D', 'O modelo erra mais quando o texto é longo?',
      'se impor limite de tamanho reduz risco',
      'dado', 'a acurácia cair com o tamanho'),
    Q(40, 'D', 'Os erros se repetem entre chamadas, ou votar em três resolve?',
      'se a votação é salvaguarda real ou teatro',
      'dado', 'o erro se mostrar determinístico'),

    # ------------------------------------------------------------- E · segurança
    Q(41, 'E', 'Qual é a superfície de ataque real deste contrato?',
      'o que precisa de defesa',
      'dado', 'aparecer vetor novo que atinja outro campo'),
    Q(42, 'E', 'Sanitizar a entrada restaura a resistência à ordem direta?',
      'se a mitigação que o guia prescreve funciona',
      'medicao', 'a sanitização não reduzir a taxa de virada'),
    Q(43, 'E', 'Uma pergunta-sentinela detecta o texto que tenta instruir o classificador?',
      'se dá para detectar em vez de só filtrar',
      'medicao', 'a sentinela ter recall baixo ou alarme falso alto'),
    Q(44, 'E', 'Delimitar o texto do cliente com marcadores explícitos reduz a virada?',
      'se a defesa cabe na instrução, sem código novo',
      'medicao', 'a delimitação não reduzir a taxa de virada'),
    Q(45, 'E', 'O corte de confiança serve como defesa contra injeção?',
      'se o corte pode ser contado como controle de segurança',
      'dado', 'nenhuma virada passar do corte em nenhum corpus'),
    Q(46, 'E', 'Qual defesa tem o melhor custo-benefício?',
      'qual mitigação implementar primeiro',
      'medicao', 'outra defesa superar em redução por unidade de custo'),
    Q(47, 'E', 'O guarda de comando pode ser ativado com segurança?',
      'sair do modo sombra ou não',
      'dado', 'aparecer irreversível liberado em qualquer corte'),
    Q(48, 'E', 'Qual o pior resultado possível se uma injeção passar?',
      'o desenho do controle compensatório',
      'dado', 'a classe alvo da injeção deixar de ser acionável'),
    Q(49, 'E', 'A resistência depende da mensagem — dá para prever qual mensagem é frágil?',
      'se é possível alertar caso a caso',
      'medicao', 'não existir sinal que separe frágil de resistente'),
    Q(50, 'E', 'Quanto custa a defesa recomendada, por mil decisões?',
      'se a defesa cabe no custo por decisão',
      'conta', 'a defesa passar a custar mais que a decisão'),

    # ------------------------------------------------------------- F · escopo
    Q(51, 'F', 'Em que línguas o resultado está medido?',
      'onde o estudo pode ser citado sem ressalva',
      'dado', 'aparecer diferença significativa entre línguas'),
    Q(52, 'F', 'Em que domínios o resultado está medido?',
      'onde o estudo pode ser citado sem ressalva',
      'dado', 'um domínio novo cair abaixo do aceitável'),
    Q(53, 'F', 'A seleção de contexto vale em prosa ou só em código?',
      'onde aplicar a Aplicação 3',
      'dado', 'o Jev superar o BM25 em prosa'),
    Q(54, 'F', 'O estudo vale para texto real, ou só para caso construído?',
      'o que declarar como limite',
      'dado', 'entrar corpus de produção no estudo'),
    Q(55, 'F', 'Qual é o maior buraco de escopo hoje?',
      'a próxima coleta',
      'dado', 'o buraco ser fechado'),
    Q(56, 'F', 'O resultado se mantém em contexto muito grande?',
      'se há limite de tamanho a impor',
      'dado', 'aparecer degradação abaixo do limite medido'),
    Q(57, 'F', 'O resultado se mantém em taxonomia grande?',
      'quão fina a taxonomia pode ser',
      'dado', 'a degradação começar antes do limite medido'),
    Q(58, 'F', 'O resultado se mantém sob ruído de digitação?',
      'se o canal precisa de normalização prévia',
      'dado', 'a degradação aparecer em nível de ruído plausível'),
    Q(59, 'F', 'O que muda se o canal tiver outra mistura de assuntos?',
      'como estimar a acurácia esperada do seu canal',
      'dado', 'a variação entre misturas passar de 5 pontos'),
    Q(60, 'F', 'Que evidência falta para ampliar o escopo com segurança?',
      'o desenho da próxima rodada',
      'dado', 'a evidência ser coletada'),

    # ------------------------------------------------------------- G · alternativas
    Q(61, 'G', 'Contra regra por palavra-chave, qual a diferença medida?',
      'se vale trocar o método atual',
      'dado', 'a diferença cair abaixo de 10 pontos'),
    Q(62, 'G', 'Contra BM25 em código, qual a diferença medida?',
      'se vale pagar uma chamada para ordenar código',
      'dado', 'o BM25 empatar em código'),
    Q(63, 'G', 'Contra BM25 em prosa, qual a diferença medida?',
      'se vale pagar uma chamada para ordenar prosa',
      'dado', 'o Jev passar a ganhar em prosa'),
    Q(64, 'G', 'Contra LLM genérico barato em acurácia, qual a diferença?',
      'se o preço quatro vezes maior se justifica por acurácia',
      'dado', 'a vantagem passar a existir sob critério independente'),
    Q(65, 'G', 'Contra LLM genérico barato sob injeção, qual a diferença?',
      'se o preço se justifica por robustez',
      'dado', 'um comparador igualar a resistência do Jev'),
    Q(66, 'G', 'Contra revisão humana, qual a diferença de custo?',
      'quanto a automação parcial economiza',
      'conta', 'o custo-hora declarado mudar'),
    Q(67, 'G', 'Contra revisão humana, qual a diferença de acurácia?',
      'se a automação perde qualidade',
      'dado', 'aparecer medição de acurácia humana no mesmo material'),
    Q(68, 'G', 'Contra não fazer nada, o que se perde?',
      'o custo da inação',
      'conta', 'o volume declarado mudar'),
    Q(69, 'G', 'Qual alternativa vence em cada aplicação?',
      'a escolha de método por aplicação',
      'dado', 'qualquer pareamento inverter'),
    Q(70, 'G', 'Existe cenário em que uma alternativa domina o Jev?',
      'onde não usar o Jev',
      'dado', 'o cenário deixar de existir'),

    # ------------------------------------------------------------- H · operação
    Q(71, 'H', 'Qual latência esperar, mediana e cauda?',
      'o orçamento de tempo do fluxo',
      'dado', 'a latência mediana passar de 1 segundo'),
    Q(72, 'H', 'A latência cabe num gancho interativo de editor?',
      'se dá para usar no caminho quente',
      'dado', 'a cauda passar do limite tolerável do gancho'),
    Q(73, 'H', 'Qual a taxa de falha de transporte a esperar?',
      'o desenho da repescagem',
      'dado', 'a taxa passar de 3%'),
    Q(74, 'H', 'Em quanto tempo o modelo já derivou, na prática?',
      'a frequência de reverificação',
      'dado', 'uma segunda deriva aparecer em prazo diferente'),
    Q(75, 'H', 'Quanto custa monitorar o comportamento continuamente?',
      'se o monitoramento entra no orçamento',
      'conta', 'o custo por corrida mudar'),
    Q(76, 'H', 'Qual a frequência adequada de canário?',
      'a configuração do agendamento',
      'conta', 'a taxa observada de deriva mudar'),
    Q(77, 'H', 'O que fazer quando um canário reprova?',
      'o procedimento operacional',
      'dado', 'a reprovação passar a ter causa diagnosticável de fora'),
    Q(78, 'H', 'Existe limite conhecido de paralelismo?',
      'quantas linhas usar na coleta',
      'dado', 'o provedor mudar o limite de taxa'),
    Q(79, 'H', 'Quanto do estudo é reprodutível hoje, por comando?',
      'o que um terceiro consegue refazer',
      'dado', 'algum artefato deixar de ser regerável'),
    Q(80, 'H', 'Qual a dívida operacional aberta?',
      'o que consertar antes de escalar',
      'dado', 'a dívida ser paga'),

    # ------------------------------------------------------------- I · governança
    Q(81, 'I', 'Quantos números publicados são conferidos automaticamente?',
      'quanta confiança a documentação merece',
      'dado', 'a cobertura de auditoria cair'),
    Q(82, 'I', 'Quantas afirmações são demonstradas, e quantas são só direção?',
      'o que pode ser dito sem ressalva',
      'dado', 'uma direção passar a ter significância'),
    Q(83, 'I', 'Quantas afirmações publicadas já caíram?',
      'quanto desconto aplicar às afirmações atuais',
      'dado', 'outra afirmação cair'),
    Q(84, 'I', 'Quanto tempo se passou entre publicar e corrigir, nas que caíram?',
      'quanto vale o mecanismo de auditoria',
      'dado', 'uma correção demorar muito mais que as anteriores'),
    Q(85, 'I', 'Um terceiro consegue refazer o estudo com o que está no repositório?',
      'se o trabalho é publicável',
      'dado', 'faltar artefato ou instrução'),
    Q(86, 'I', 'Há conflito de interesse na escrita do gabarito?',
      'quanto peso dar aos resultados de acurácia',
      'dado', 'o gabarito passar a ser de terceiro em todas as rodadas'),
    Q(87, 'I', 'A taxa de falsificação das cem hipóteses é compatível com acaso?',
      'se as falsificações merecem crédito individual',
      'conta', 'a taxa observada cair para o esperado sob acaso'),
    Q(88, 'I', 'O que é publicável externamente hoje sem ressalva?',
      'o que pode virar material externo',
      'dado', 'uma afirmação publicável cair'),
    Q(89, 'I', 'Qual a afirmação mais frágil ainda de pé?',
      'onde olhar antes de citar',
      'dado', 'a afirmação ser confirmada ou cair'),
    Q(90, 'I', 'O orçamento autorizado foi respeitado?',
      'se há autorização para continuar',
      'dado', 'o gasto passar do teto'),

    # ------------------------------------------------------------- J · próximos movimentos
    Q(91, 'J', 'Qual a próxima medição de maior retorno por dólar?',
      'a próxima rodada',
      'dado', 'uma lacuna maior aparecer'),
    Q(92, 'J', 'Quanto custaria medir o acerto do roteador em produção?',
      'se essa lacuna é barata de fechar',
      'conta', 'o volume de pedidos registrados mudar'),
    Q(93, 'J', 'Quanto custaria anotar 200 mensagens reais?',
      'se a lacuna que destrava tudo é de dinheiro ou de acesso',
      'conta', 'o custo-hora de anotação mudar'),
    Q(94, 'J', 'O que destrava a adoção em escala?',
      'onde pedir ajuda',
      'dado', 'o destravamento acontecer'),
    Q(95, 'J', 'Qual experimento derrubaria a recomendação principal?',
      'o teste adversarial a fazer antes de escalar',
      'dado', 'o experimento ser feito'),
    Q(96, 'J', 'Quanto resta do orçamento, e o que ele compra?',
      'o tamanho do próximo programa',
      'conta', 'o teto ser revisto'),
    Q(97, 'J', 'Que fração das cem hipóteses aponta para trabalho novo?',
      'quanto trabalho a varredura gerou',
      'dado', 'as pendências serem fechadas'),
    Q(98, 'J', 'Qual risco identificado ainda não tem mitigação medida?',
      'o que não pode ir para produção ainda',
      'dado', 'a mitigação ser medida'),
    Q(99, 'J', 'O que deve entrar em produção primeiro, e com que salvaguarda?',
      'o plano de implantação',
      'dado', 'a salvaguarda se mostrar insuficiente'),
    Q(100, 'J', 'Se o trabalho parar hoje, o que fica de valor reaproveitável?',
      'o que preservar',
      'dado', 'um artefato deixar de ser reaproveitável'),
]

POR_ID = {q['id']: q for q in PERGUNTAS}

assert len(PERGUNTAS) == 100, f'o registro tem {len(PERGUNTAS)}, não 100'
assert len(POR_ID) == 100, 'há identificador repetido'
