'use strict';
const $=s=>document.querySelector(s);
let state={tools:[],runs:[],wallet:{}},category='Todas',selected=null,selectedRun=null,busy=false;
const money=n=>typeof n==='number'?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumFractionDigits:6}).format(n):'—';
const decisions={every_live_smoke_passed:'Every validado em 2 funções sintéticas: distinguiu limpeza de espaços de uma soma. Não é avaliação de bugs em produção.',direct_candidate_live_smoke_passed:'CLI validado com inferência real: 7 de 7 casos sintéticos corretos. Qualidade em produção ainda não medida.',direct_candidate_live_pending:'Candidato direto ao Codex. Falta medir qualidade em tarefas reais.',scripted_demo_only:'Demonstração testada em modo programado; não é integração operacional do Codex.',offline_replay_available:'Replays históricos disponíveis. Os resultados variam conforme o conjunto de dados.',built_database_and_accounts_pending:'Compilado. Uso como bot depende de banco PostgreSQL e contas configuradas.',benchmark_live_pending:'Instrumento pronto para avaliar. Falta rodada com inferência real.',static_checks_pass_live_review_pending:'Verificações estáticas aprovadas; precisão da revisão ainda não medida.',built_search_credentials_and_wallet_adapter_pending:'Compilado; busca depende de Search1API e adaptação financeira.',live_browser_and_wallet_adapter_pending:'Testes locais aprovados; navegação real e integração financeira pendentes.',synthetic_demo_available:'Demonstração sintética disponível. Não representa qualidade de um modelo real.',ui_ready_inference_blocked_missing_wallet:'Interface validada. Inferência depende da prontidão atual da carteira.',cpu_environment_ready_weights_not_validated:'Ambiente CPU instalado. Pesos e desempenho de inferência ainda não avaliados.',pi_extension_not_codex_integration:'Extensão do Pi. Instalação local não a transforma em extensão do Codex.',custom_mocked_worker_checks_only:'Verificações próprias com respostas simuladas; classificação real não medida.',adoption_pending_failures:'Falhas de testes em aberto. Consulte os resultados antes de adotar.'};
function node(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function toast(text){$('#toast').textContent=text;$('#toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').hidden=true,6500);}
async function api(path,body){const r=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json','X-Harness-Token':state.token},body:JSON.stringify(body)}:{});const data=await r.json();if(!r.ok)throw Error(data.error||'Falha na operação');return data;}
async function refresh(){try{state=await api('/api/state');$('#connection').textContent='Local conectado';render();}catch(e){$('#connection').textContent='Servidor indisponível';if(!state.token)toast(e.message);}}
function show(view){document.querySelectorAll('.view').forEach(e=>e.hidden=e.id!==view);document.querySelectorAll('.nav').forEach(e=>e.classList.toggle('active',e.dataset.view===view));}
document.querySelectorAll('.nav').forEach(e=>e.onclick=()=>show(e.dataset.view));
$('#refresh').onclick=refresh;$('#search').oninput=renderTools;
function render(){const w=state.wallet;$('#balance').textContent=money(w.remaining_usd);$('#cap').textContent='Teto '+money(w.wallet_cap_usd);$('#wallet-status').textContent=w.paid_ready?'Pronta para uso':'Indisponível';$('#wallet-status').title=w.reason||'';$('#wallet-dot').textContent=w.paid_ready?'●':'○';$('#budget-bar').style.width=(w.wallet_cap_usd?Math.max(0,Math.min(100,(w.remaining_usd/w.wallet_cap_usd)*100)):0)+'%';$('#installed').textContent=state.tools.filter(t=>t.installed).length;$('#passing').textContent=state.tools.reduce((n,t)=>n+(t.tests_passed||0),0).toLocaleString('pt-BR');$('#failures').textContent=state.tools.reduce((n,t)=>n+(t.tests_failed||0),0);const active=state.runs.filter(r=>['executando','cancelando'].includes(r.status)).length;$('#active-jobs').textContent=active;$('#running-count').textContent=active;$('#judge').disabled=!w.paid_ready||busy;$('#nav-count').textContent=state.tools.length;
 const filters=['Todas',...new Set(state.tools.map(t=>t.group))];$('#filters').replaceChildren(...filters.map(f=>{const b=node('button',f,f===category?'selected':'');b.setAttribute('aria-pressed',f===category);b.onclick=()=>{category=f;render();};return b;}));renderTools();renderRuns();if(selected&&$('#detail').open)renderDetail();if(selectedRun&&$('#run-detail').open)renderRun();}
function renderTools(){const q=$('#search').value.toLocaleLowerCase();const rows=state.tools.filter(t=>(category==='Todas'||t.group===category)&&`${t.name} ${t.description}`.toLocaleLowerCase().includes(q));$('#tools').replaceChildren(...rows.map(t=>{const b=node('button',undefined,'tool');b.setAttribute('aria-label',`Gerenciar ${t.name}`);const top=node('div',undefined,'tool-top');top.append(node('span',t.group.toUpperCase()),node('span',t.enabled?'↗':'Ⅱ'));const bottom=node('div',undefined,'tool-bottom');bottom.append(node('span',t.tests_passed===null?'Verificações estáticas':`${t.tests_passed} aprovados${t.tests_failed?' · '+t.tests_failed+' falhas':''}`),node('span',!t.enabled?'Pausada':t.tests_failed?'Com ressalvas':'Instalada','tag '+(!t.enabled?'paused':t.tests_failed?'warn':'')));b.append(top,node('h3',t.name),node('p',t.description),bottom);b.onclick=()=>{selected=t.system;renderDetail();$('#detail').showModal();};return b;}));if(!rows.length)$('#tools').append(node('div','Nenhuma ferramenta encontrada. Tente outro termo.','empty'));}
function renderDetail(){const t=state.tools.find(t=>t.system===selected);$('#detail-title').textContent=t.name;$('#detail-group').textContent=t.group;$('#detail-desc').textContent=t.description;$('#detail-decision').textContent=decisions[t.decision]||t.decision;$('#revision').textContent=t.revision;$('#detail-status').replaceChildren(node('span',t.installed?'Fontes presentes nesta máquina':'Fontes ausentes','tag'));$('#detail-tests').replaceChildren(...[['Aprovados',t.tests_passed],['Falhas',t.tests_failed],['Ignorados',t.tests_skipped]].map(([label,value])=>{const n=node('div');n.append(node('strong',value??'—'),node('span',label));return n;}));$('#enabled').checked=t.enabled;$('#actions').replaceChildren(...t.actions.map(a=>{const b=node('button',a.label+(a.paid?' · usa saldo':''),'action');b.disabled=!t.enabled||!t.installed||(a.paid&&!state.wallet.paid_ready)||state.runs.some(r=>r.tool===t.system&&['executando','cancelando'].includes(r.status));b.onclick=()=>run(t.system,a.id);return b;}));}
$('#enabled').onchange=async e=>{try{await api('/api/preference',{tool:selected,enabled:e.target.checked});await refresh();}catch(err){toast(err.message);await refresh();}};
$('#close-detail').onclick=()=>$('#detail').close();$('#close-run').onclick=()=>$('#run-detail').close();
async function run(tool,action,payload){try{busy=true;await api('/api/run',{tool,action,payload});$('#detail').close();show('history');toast('Operação iniciada. Acompanhe o resultado abaixo.');await refresh();}catch(e){toast(e.message);}finally{busy=false;$('#judge').disabled=!state.wallet.paid_ready;}}
function renderRuns(){const labels={executando:'Em execução',concluido:'Concluído',falhou:'Falhou',cancelado:'Cancelado',cancelando:'Cancelando',interrompido:'Interrompido'};$('#runs').replaceChildren(...state.runs.map(r=>{const el=node('article',undefined,'run');const info=node('div',undefined,'run-info');info.append(node('strong',(state.tools.find(t=>t.system===r.tool)?.name||'JEV / Apoio')+' · '+r.action),node('small',new Date(r.started*1000).toLocaleString('pt-BR')+(r.client_id?' · '+r.client_id:'')+(r.finished?' · '+Math.round(r.finished-r.started)+' s':'')));el.append(node('span',labels[r.status]||r.status,'tag '+(['falhou','interrompido'].includes(r.status)?'warn':'')),info);const view=node('button','Ver saída');view.onclick=()=>{selectedRun=r.id;renderRun();$('#run-detail').showModal();};el.append(view);if(r.status==='executando'&&r.tool!=='workbench'){const cancel=node('button','Cancelar','cancel');cancel.onclick=async()=>{try{await api('/api/cancel',{id:r.id});await refresh();}catch(e){toast(e.message);}};el.append(cancel);}return el;}));if(!state.runs.length)$('#runs').append(node('div','Seu histórico começa aqui. Escolha uma ferramenta e execute uma operação.','empty'));}
function renderRun(){const r=state.runs.find(r=>r.id===selectedRun);if(!r)return;$('#run-title').textContent=(state.tools.find(t=>t.system===r.tool)?.name||'JEV / Apoio')+' · '+r.action;$('#run-status').textContent=r.status+(r.code!==null?' · código de saída '+r.code:'');$('#run-output').textContent=r.output||'Aguardando a conclusão do processo. A saída será preservada aqui.';}
$('#state').oninput=()=>$('#char-count').textContent=$('#state').value.length.toLocaleString('pt-BR')+' / 12.000';
$('#example').onclick=()=>{const examples={log:'ERROR: ModuleNotFoundError: No module named requests. O processo de importação encerrou com código 1.',evidence:'AFIRMAÇÃO: O pagamento foi realizado.\nFONTE: O pagamento foi agendado para amanhã, mas ainda não foi executado.',context:'PERGUNTA: Como exportar registros em CSV?\nTRECHO: Abra Registros, clique Exportar e selecione CSV. Somente os registros do filtro atual serão incluídos.'};$('#state').value=examples[$('#task').value];$('#state').oninput();};
$('#judge-form').onsubmit=e=>{e.preventDefault();if(!busy)run('workbench',$('#task').value,{text:$('#state').value});};
refresh();setInterval(()=>{if(!document.hidden)refresh();},4000);
