"""Monta pares (contexto anterior, pedido) a partir dos transcripts reais do Claude Code.

O teste anterior mostrou que 54 de 60 pedidos reais são continuações: o texto do prompt, lido
sozinho, não diz o que precisa ser feito. O hook `UserPromptSubmit` recebe o caminho da
transcrição, ou seja, o contexto que falta está ao alcance. Esta amostra existe para medir se
dar esse contexto ao Jev muda alguma coisa.

O contexto é curto de propósito — a última fala do assistente e o pedido anterior do usuário,
truncados. Um contexto grande custaria mais em token do que o roteador economiza.

    python avaliacao/amostrar_com_contexto.py --n 60
"""
import argparse
import json
import random
from pathlib import Path

RAIZ = Path(__file__).resolve().parents[1]
PROJETOS = Path.home() / '.claude' / 'projects'
DESTINO = RAIZ / 'avaliacao' / 'amostra-com-contexto.json'
SEMENTE = 20260919

LIMITE_ASSISTENTE = 700
LIMITE_USUARIO = 300


def texto(mensagem):
    if isinstance(mensagem, str):
        return mensagem
    if isinstance(mensagem, list):
        partes = []
        for bloco in mensagem:
            if isinstance(bloco, dict) and bloco.get('type') == 'text':
                partes.append(bloco.get('text') or '')
        return '\n'.join(partes)
    return ''


# O transcript grava como "user" várias coisas que o Igor não digitou: aviso de tarefa que
# terminou, saída de comando local, resumo de compactação, resultado de hook. O hook
# `UserPromptSubmit` não dispara em nenhuma delas, então elas não podem entrar na amostra --
# entraram na primeira tentativa e a poluíram inteira.
NAO_E_PEDIDO = ('<task-notification>', '<local-command-stdout>', '<command-name>',
                '<command-message>', '<system-reminder>', '<local-command-caveat>',
                'This session is being continued from a previous conversation',
                'Caveat: The messages below were generated by the user while running',
                '[Request interrupted')


def e_digitado(texto):
    return not any(texto.lstrip().startswith(marca) for marca in NAO_E_PEDIDO)


def pares_de(caminho):
    """Devolve os pedidos do usuário com a conversa imediatamente anterior."""
    falas = []
    for linha in caminho.read_text(encoding='utf-8', errors='replace').splitlines():
        try:
            registro = json.loads(linha)
        except ValueError:
            continue
        if registro.get('isMeta') or registro.get('isSidechain'):
            continue
        mensagem = registro.get('message')
        if not isinstance(mensagem, dict):
            continue
        papel = mensagem.get('role')
        conteudo = texto(mensagem.get('content')).strip()
        if papel in ('user', 'assistant') and conteudo:
            falas.append((papel, conteudo))

    saida = []
    for i, (papel, conteudo) in enumerate(falas):
        if papel != 'user' or len(conteudo) < 25 or conteudo.startswith('/'):
            continue
        if not e_digitado(conteudo):
            continue
        anterior_assistente = ''
        anterior_usuario = ''
        for papel_anterior, conteudo_anterior in reversed(falas[:i]):
            if papel_anterior == 'assistant' and not anterior_assistente:
                anterior_assistente = conteudo_anterior[-LIMITE_ASSISTENTE:]
            elif papel_anterior == 'user' and not anterior_usuario:
                anterior_usuario = conteudo_anterior[:LIMITE_USUARIO]
            if anterior_assistente and anterior_usuario:
                break
        if not anterior_assistente:
            continue  # sem contexto anterior não há o que comparar
        saida.append({'pedido': conteudo[:1200],
                      'anterior_usuario': anterior_usuario,
                      'anterior_assistente': anterior_assistente,
                      'projeto': caminho.parent.name})
    return saida


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--n', type=int, default=60)
    args = parser.parse_args()

    todos = []
    for caminho in sorted(PROJETOS.glob('*/*.jsonl')):
        try:
            todos.extend(pares_de(caminho))
        except OSError:
            continue

    vistos, unicos = set(), []
    for par in todos:
        marca = par['pedido'].strip().lower()
        if marca in vistos:
            continue
        vistos.add(marca)
        unicos.append(par)

    random.Random(SEMENTE).shuffle(unicos)
    amostra = [{'id': f'ctx-{i + 1:03d}', **p} for i, p in enumerate(unicos[:args.n])]
    DESTINO.write_text(json.dumps(
        {'semente': SEMENTE, 'universo': len(unicos), 'amostra': amostra},
        ensure_ascii=False, indent=1), encoding='utf-8')
    print(f'{len(amostra)} pares sorteados de {len(unicos)} distintos '
          f'-> {DESTINO.relative_to(RAIZ)}')


if __name__ == '__main__':
    main()
