'use strict';
const $ = s => document.querySelector(s);
const LABELS = {planned:'Planejado',running:'Em andamento',done:'Concluído',blocked:'Bloqueado',paused:'Pausado',completed:'Concluída',failed:'Falhou'};
const PHASES = {simple:'Rodada simples',deep:'Aprofundamento',pilot:'Piloto',confirmation:'Confirmação'};
const EVIDENCE = {offline:'Teste offline',replay:'Resposta armazenada',live_component:'Inferência real',mock_integration:'Integração simulada',live_e2e:'Fluxo completo'};
const TITLES = {overview:'Terminal de execução',execution:'Execução',systems:'Sistemas',results:'Dados e resultados',metrics:'Métricas explicadas',budget:'Orçamento',files:'Arquivos e fontes'};
const STAGES = [
 ['Estudo e auditoria','Plano, fontes e 96 decisões históricas conferidas.'],
 ['Preparar dados e ambiente','Importar evidências, conferir dependências e rubricas.'],
 ['Validar o controle de gastos','Reservas, falhas simuladas e canários de contrato.'],
 ['Testar os 15 sistemas','Uma rodada simples, com evidência por sistema.'],
 ['Executar o piloto','120 casos e desenho fatorial de diagnóstico.'],
 ['Congelar os conjuntos principais','Gabaritos, grupos e partições de teste reservadas.'],
 ['Aprofundar por família','Comparações pareadas de qualidade, custo e tempo.'],
 ['Confirmar os candidatos','Casos novos e hipóteses prioritárias.'],
 ['Decidir e documentar','Adotar, ajustar, manter consultivo ou encerrar o uso.']
];
const STORE='jev-lab-execution-v1';
let state=structuredClone(INITIAL_STATE), mode='loading', saving=false, locked=false, activeView='overview', pendingImport=null, pageNumber=1;
let filters={systemSearch:'',family:'',executionPhase:'simple',executionStatus:'',source:'new',resultSystem:'',resultSearch:'',resultCorrect:'',resultSplit:'',resultMode:''};
let toastTimer;
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=(n,d=6)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'USD',minimumFractionDigits:2,maximumFractionDigits:d}).format(n);
const number=n=>new Intl.NumberFormat('pt-BR').format(n);
const date=x=>x&&Number.isFinite(Date.parse(x))?new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(x)):'Sem data';
const badge=status=>`<span class="badge ${esc(status)}">${esc(LABELS[status]||status)}</span>`;
const system=id=>PLAN.systems.find(s=>s.id===id);
const progress=(id,phase)=>state.system_progress[id]?.[phase]||'planned';
const stageStatus=i=>i===0?'done':state.stage_progress[String(i)]?.status||'planned';
const opts=(items,selected,all)=>`${all!==undefined?`<option value="">${esc(all)}</option>`:''}${Object.entries(items).map(([v,t])=>`<option value="${esc(v)}"${v===selected?' selected':''}>${esc(t)}</option>`).join('')}`;
const empty=(title,text,button='')=>`<div class="empty"><span class="empty-icon">↳</span><h3>${esc(title)}</h3><p>${esc(text)}</p>${button}</div>`;
const intro=(k,title,description,action='')=>`<div class="page-intro"><div><span class="eyebrow">${esc(k)}</span><h1>${esc(title)}</h1><p>${esc(description)}</p></div>${action}</div>`;
const stable=x=>Array.isArray(x)?'['+x.map(stable).join(',')+']':x&&typeof x==='object'?'{'+Object.keys(x).sort().map(k=>JSON.stringify(k)+':'+stable(x[k])).join(',')+'}':JSON.stringify(x);
function toast(text){clearTimeout(toastTimer);$('#toast').textContent=text;$('#toast').hidden=false;toastTimer=setTimeout(()=>$('#toast').hidden=true,6000)}
function notice(text){$('#persistentNotice').hidden=!text;$('#persistentNotice').textContent=text||''}
function connection(){
 const labels={api:'Conectado à pasta',local:'Salvo neste navegador',disconnected:'Conexão interrompida',loading:'Abrindo dados…'};
 $('#connectionText').textContent=labels[mode];$('#connectionDot').className=mode==='api'?'online':mode==='disconnected'?'error':'';
 $('#saveHint').textContent=mode==='api'?'Atualização automática a cada 5 segundos.':mode==='local'?'Exporte um backup para levar suas alterações.':'Alterações só são liberadas com armazenamento disponível.';
 $('#updatedAt').textContent='Dados: '+date(state.updated_at);
}
function metrics(){
 const attempts=state.runs.flatMap(r=>r.attempts), decisions=state.runs.flatMap(r=>r.decisions);
 const spent=attempts.reduce((n,a)=>n+Math.round((a.cost_usd||0)*1e9),0)/1e9;
 const reserved=attempts.reduce((n,a)=>n+Math.round((a.reserved_usd||0)*1e9),0)/1e9;
 return {attempts,decisions,spent,reserved,unknown:attempts.filter(a=>a.cost_usd===null).length,
  simpleDone:PLAN.systems.filter(s=>progress(s.id,'simple')==='done').length,
  deepDone:PLAN.systems.filter(s=>progress(s.id,'deep')==='done').length,
  covered:new Set(state.runs.map(r=>r.system_id)).size,
  completed:state.runs.filter(r=>r.status==='completed').length};
}
function optionsStatus(value){return opts(Object.fromEntries(['planned','running','done','blocked','paused'].map(x=>[x,LABELS[x]])),value)}
function timeline(editable=false){return STAGES.map(([name,desc],i)=>`<div class="step ${stageStatus(i)}"><span class="number">${stageStatus(i)==='done'?'✓':String(i).padStart(2,'0')}</span><div><h3>${esc(name)}</h3><p>${esc(desc)}</p></div>${editable&&i>0?`<select class="table-status" data-stage="${i}" aria-label="Status da etapa ${i}">${optionsStatus(stageStatus(i))}</select>`:badge(stageStatus(i))}</div>`).join('')}
function activity(){
 const fixed={at:INITIAL_STATE.updated_at,text:'Auditoria offline concluída: 96 decisões conferidas, 48 casos únicos, nenhuma inferência nova.',kind:'evidence'};
 return [...state.events].reverse().slice(0,5).concat(fixed).slice(0,6).map(e=>`<div class="event"><i class="dot"></i><div><p>${esc(e.text)}</p><small>${date(e.at)} · ${e.kind==='manual'?'ACOMPANHAMENTO':e.kind==='import'?'IMPORTAÇÃO':'EVIDÊNCIA'}</small></div></div>`).join('');
}
function overview(){const m=metrics(),stagesDone=STAGES.filter((s,i)=>stageStatus(i)==='done').length;
 return `<div class="hero"><div class="hero-main"><span class="eyebrow">JEV / PROGRAMA DE AVALIAÇÃO</span><h1>${m.attempts.length?'Da execução à evidência.':'Pronto para a primeira rodada.'}</h1><p>Acompanhe cada etapa, confira os dados e veja o que cada sistema entrega. O histórico do Hermes permanece separado dos novos testes.</p><button class="button dark" data-go="execution">Acompanhar execução <span>↗</span></button></div><div class="hero-side"><div><span class="eyebrow">ETAPAS DO PLANO</span><div class="big">${stagesDone}<span style="font-size:23px;color:#b5c7ac"> / 9</span></div></div><div><div class="progress-track"><i style="width:${stagesDone/9*100}%"></i></div><p>Estudo concluído + acompanhamento registrado.<br>Conclusão de etapa não é aprovação científica.</p></div></div></div>
 <div class="kpis"><div class="kpi"><div class="label">Rodada simples <span>↗</span></div><strong>${m.simpleDone}<span class="muted" style="font-size:18px"> / 15</span></strong><small>Conclusões registradas no acompanhamento</small></div><div class="kpi"><div class="label">Novas execuções <span>◈</span></div><strong>${state.runs.length}</strong><small>${m.covered} sistemas com dados · ${m.attempts.length} tentativas</small></div><div class="kpi"><div class="label">Custo novo conhecido <span>↗</span></div><strong>${money(m.spent,4)}</strong><small>${m.unknown?m.unknown+' tentativas com custo desconhecido':'Dados financeiros das execuções importadas'}</small></div><div class="kpi"><div class="label">Base histórica <span>▥</span></div><strong>96</strong><small>Decisões do PDF · 48 casos únicos</small></div></div>
 <div class="columns"><div class="panel"><div class="panel-head"><h2>Roteiro de execução</h2><button class="text-link" data-go="execution">Ver acompanhamento</button></div><div class="timeline">${timeline()}</div></div><div><div class="panel"><div class="panel-head"><h2>Últimos registros</h2><span class="eyebrow">LOCAL</span></div><div class="activity">${activity()}</div></div><div class="panel"><div class="panel-head"><h2>Novas evidências</h2><button class="text-link" data-go="results">Ver dados</button></div>${state.runs.length?`<div class="panel-body"><h2>${number(m.decisions.length)} decisões registradas</h2><p class="muted small">${m.completed} execuções concluídas. Abra os resultados para consultar falhas, casos, partições e proveniência.</p></div>`:empty('Os resultados aparecerão aqui','Importe o pacote de uma execução. Não há resultados simulados preenchendo o painel.',`<button class="button" data-import>Importar resultados</button>`)}</div><div class="hint">Próximo marco: conferir ambiente e dados, validar o controle financeiro e executar a rodada simples dos 15 sistemas.</div></div></div>`;
}
function execution(){
 const selected=PLAN.systems.filter(s=>!filters.executionStatus||progress(s.id,filters.executionPhase)===filters.executionStatus);
 return intro('ACOMPANHAMENTO','Cada sistema, cada rodada.','Registre o avanço e os bloqueios. Os resultados reais entram por importação, independentemente destes status.')+
 `<div class="section-tabs"><button data-phase="simple" class="${filters.executionPhase==='simple'?'active':''}">01 / Rodada simples</button><button data-phase="deep" class="${filters.executionPhase==='deep'?'active':''}">02 / Aprofundamento</button></div><div class="filters"><label>Situação<select id="executionStatus">${opts(Object.fromEntries(Object.keys(LABELS).filter(x=>!['completed','failed'].includes(x)).map(x=>[x,LABELS[x]])),filters.executionStatus,'Todas as situações')}</select></label><label class="search"><span class="small">${filters.executionPhase==='simple'?'156 unidades heterogêneas · até 168 tentativas Jev + 18 auxiliares':'Bases compartilhadas de classificação, busca, código e agentes'}</span></label><button class="button" id="exportProgress">↓ Exportar acompanhamento</button></div>
 <div class="panel"><div class="table-wrap"><table><thead><tr><th>Sistema</th><th>Família</th><th>${filters.executionPhase==='simple'?'Rodada simples':'Protocolo'}</th><th>Status registrado</th><th>Execuções importadas</th><th></th></tr></thead><tbody>${selected.map(s=>`<tr><td><button class="name-button" data-system="${s.id}">${esc(s.name)}</button><br><small>${s.id}</small></td><td>${esc(s.family)}</td><td>${filters.executionPhase==='simple'?s.smoke_units+' '+esc(s.smoke_unit):'Ver ficha detalhada'}</td><td><select data-progress="${s.id}" class="table-status" aria-label="Status ${esc(s.name)}">${optionsStatus(progress(s.id,filters.executionPhase))}</select></td><td>${state.runs.filter(r=>r.system_id===s.id&&r.phase===filters.executionPhase).length}</td><td><button class="text-link" data-system="${s.id}">Ficha ↗</button></td></tr>`).join('')}</tbody></table></div>${selected.length?'':empty('Nenhum sistema neste filtro','Escolha outra situação para ver o acompanhamento.')}</div><div class="hint">Alterar o status registra acompanhamento, não comprova execução ou qualidade. Uma inferência real deve ter dados e nível de evidência registrados.</div><div class="panel"><div class="panel-head"><h2>Marcos do plano</h2><span class="small muted">Etapa 0 verificada · demais etapas editáveis</span></div><div class="timeline">${timeline(true)}</div></div>`;
}
function systemsView(){const q=filters.systemSearch.toLowerCase();const selected=PLAN.systems.filter(s=>(!filters.family||s.family===filters.family)&&[s.name,s.question,s.family,s.smoke].join(' ').toLowerCase().includes(q));
 return intro('15 SISTEMAS / PROTOCOLOS','O que estamos testando.','Hipóteses, comparadores e critérios de decisão do plano científico. Abra uma ficha para ver o protocolo e registrar observações.')+
 `<div class="filters"><label class="search">Buscar sistema ou pergunta<input id="systemSearch" type="search" value="${esc(filters.systemSearch)}" placeholder="Ex.: confiança, código, navegador"></label><label>Família<select id="familyFilter">${opts(Object.fromEntries([...new Set(PLAN.systems.map(s=>s.family))].sort().map(f=>[f,f])),filters.family,'Todas as famílias')}</select></label></div><p class="small muted">${selected.length} de 15 sistemas</p><div class="system-grid">${selected.map(s=>`<article class="system-card"><div class="card-top"><span class="eyebrow">${s.id} / ${esc(s.family)}</span>${badge(progress(s.id,'simple'))}</div><h3>${esc(s.name)}</h3><p>${esc(s.question)}</p><div class="card-metrics"><div><strong>${s.smoke_units}</strong><span>${esc(s.smoke_unit)} na rodada simples</span></div><div><strong>${state.runs.filter(r=>r.system_id===s.id).length}</strong><span>execuções importadas</span></div></div><button class="button" data-system="${s.id}">Abrir protocolo <span>↗</span></button></article>`).join('')}</div>${selected.length?'':empty('Nenhum sistema encontrado','Tente outra palavra ou limpe o filtro de família.')}`;
}
function resultRows(){
 let rows=filters.source==='history'?HISTORY.map((r,i)=>({id:'pdf-'+i,case_id:r.case_id,task:r.app,expected:r.expected,predicted:r.predicted,correct:Number(r.correct)===1,confidence:Number(r.confidence_pdf),split:r.split,mode:r.mode,run_id:'PDF',system_id:'Hermes',source_page:r.source_page})):
 state.runs.flatMap(r=>r.decisions.map(d=>({...d,run_id:r.id,system_id:r.system_id,mode:r.phase,model:r.model,evidence:r.evidence})));
 const q=filters.resultSearch.toLowerCase();return rows.filter(r=>(!filters.resultSystem||r.system_id===filters.resultSystem)&&(!filters.resultCorrect||(filters.resultCorrect==='unknown'?r.correct===null:String(r.correct)===filters.resultCorrect))&&(!filters.resultSplit||r.split===filters.resultSplit)&&(!filters.resultMode||r.mode===filters.resultMode)&&(!q||[r.case_id,r.task,r.expected,r.predicted,r.run_id].join(' ').toLowerCase().includes(q)));
}
function resultsView(){const historic=filters.source==='history';const rows=resultRows(),maxPage=Math.max(1,Math.ceil(rows.length/25));pageNumber=Math.max(1,Math.min(pageNumber,maxPage));const shown=rows.slice((pageNumber-1)*25,pageNumber*25);const graded=rows.filter(r=>r.correct!==null),correct=graded.filter(r=>r.correct).length;
 return intro('EVIDÊNCIAS / EXPLORADOR','Os dados por trás da decisão.','Consulte cada resultado, encontre erros e exporte os registros. As métricas descritivas não substituem a análise pareada do protocolo.')+
 `<div class="section-tabs"><button data-source="new" class="${!historic?'active':''}">Novas execuções · ${state.runs.length}</button><button data-source="history" class="${historic?'active':''}">Histórico de referência · ${HISTORY.length}</button></div>
 ${historic?`<div class="hint">Transcrição do Anexo F do PDF: 96 decisões em 48 casos, 54 chamadas. Confidence arredondada. Não são novos testes dos 15 sistemas. O pacote bruto original ainda não foi importado.</div>`:''}
 ${!historic?runList():''}
 <div class="filters"><label class="search">Buscar caso ou saída<input id="resultSearch" type="search" value="${esc(filters.resultSearch)}" placeholder="ID, tarefa, gabarito ou predição"></label>${!historic?`<label>Sistema<select id="resultSystem">${opts(Object.fromEntries(PLAN.systems.map(s=>[s.id,s.name])),filters.resultSystem,'Todos')}</select></label>`:`<label>Formato<select id="resultMode">${opts({solo:'Individual',batch:'Lote'},filters.resultMode,'Todos')}</select></label>`}<label>Partição<select id="resultSplit">${opts(historic?{development:'Desenvolvimento',holdout:'Reservado'}:{pilot:'Piloto',development:'Desenvolvimento',calibration:'Calibração',test:'Teste',diagnostic:'Diagnóstico'},filters.resultSplit,'Todas')}</select></label><label>Resultado<select id="resultCorrect">${opts({true:'Acertos',false:'Erros',unknown:'Sem gabarito'},filters.resultCorrect,'Todos')}</select></label></div>
 <div class="panel"><div class="result-summary"><div><strong>${number(rows.length)}</strong><span>decisões filtradas</span></div><div><strong>${number(new Set(rows.map(r=>(r.system_id||'')+':'+r.case_id)).size)}</strong><span>IDs únicos por sistema</span></div><div><strong>${correct} / ${graded.length}</strong><span>acertos / com gabarito</span></div><div><strong>${rows.length-graded.length}</strong><span>sem gabarito</span></div><button id="exportDecisions" class="button" style="margin-left:auto;align-self:center" ${rows.length?'':'disabled'}>↓ Exportar CSV</button></div>
 ${rows.length?`<div class="table-wrap"><table><thead><tr><th>Caso / tarefa</th><th>${historic?'Formato':'Sistema'}</th><th>Partição</th><th>Gabarito</th><th>Predição</th><th>Acerto</th><th>Confidence</th><th></th></tr></thead><tbody>${shown.map(r=>`<tr><td><span class="mono">${esc(r.case_id)}</span><br><small>${esc(r.task||'')}</small></td><td>${historic?esc(r.mode):esc(r.system_id)}</td><td>${esc(r.split)}</td><td class="truncate" title="${esc(r.expected)}">${esc(r.expected??'—')}</td><td class="truncate" title="${esc(r.predicted)}">${esc(r.predicted??'—')}</td><td class="${r.correct===false?'wrong':r.correct===true?'correct':'muted'}">${r.correct===null?'—':r.correct?'Sim':'Não'}</td><td class="mono">${r.confidence==null?'—':Number(r.confidence).toLocaleString('pt-BR',{maximumFractionDigits:4})}</td><td>${historic?`<span class="small muted">p. ${r.source_page}</span>`:`<button class="text-link" data-run="${esc(r.run_id)}">Detalhes</button>`}</td></tr>`).join('')}</tbody></table></div>`:empty('Nenhuma decisão neste conjunto',state.runs.length||historic?'Ajuste os filtros para consultar outros registros.':'Importe resultados quando uma execução terminar. O histórico do Hermes já está disponível na aba ao lado.')}
 <div class="pagination"><span class="muted">Página ${pageNumber} de ${maxPage} · 25 registros por página</span><div><button class="button" id="prevPage" ${pageNumber===1?'disabled':''}>←</button> <button class="button" id="nextPage" ${pageNumber===maxPage?'disabled':''}>→</button></div></div></div><p class="small muted">Confidence é a saída do modelo, não uma probabilidade de acerto validada. Repetições, formatos e perguntas do mesmo caso não são amostras independentes.</p>`;
}
function runList(){const runs=state.runs.filter(r=>!filters.resultSystem||r.system_id===filters.resultSystem);
 return `<div class="panel"><div class="panel-head"><h2>Registro de execuções</h2><span class="small muted">${runs.length} registros</span></div>${runs.length?`<div class="table-wrap"><table><thead><tr><th>Execução</th><th>Sistema / rodada</th><th>Evidência</th><th>Tentativas</th><th>Custo conhecido</th><th>Status</th></tr></thead><tbody>${runs.map(r=>`<tr><td><button class="name-button mono" data-run="${esc(r.id)}">${esc(r.id)}</button><br><small>${date(r.started_at)}</small></td><td>${esc(system(r.system_id).name)}<br><small>${PHASES[r.phase]}</small></td><td>${EVIDENCE[r.evidence]}</td><td>${r.attempts.length}</td><td>${money(r.attempts.reduce((s,a)=>s+(a.cost_usd||0),0))}${r.attempts.some(a=>a.cost_usd===null)?' *':''}</td><td>${badge(r.status)}</td></tr>`).join('')}</tbody></table></div>`:empty('Ainda não há execuções novas','O painel está preparado para receber tentativas, decisões, custos e falhas reais.',`<button class="button" data-import>Importar pacote de resultados</button>`)}</div>`;
}
function budgetView(){const m=metrics(),historical=Number(PLAN.audit.historical_budget_from_reports.known_usd),oldReserve=Number(PLAN.audit.historical_budget_from_reports.unresolved_reserved_usd),available=5-historical-oldReserve-m.spent-m.reserved;
 return intro('FINANCEIRO / TETO GLOBAL','Cada tentativa entra na conta.','Acompanhamento financeiro informativo. Este painel não despacha chamadas, não aplica limite no provedor e não autoriza novos gastos.')+
 `<div class="columns"><div class="panel"><div class="panel-body"><span class="eyebrow">SALDO CONSERVADOR DO EXPERIMENTO</span><div class="budget-big ${available<0?'budget-warning':''}">${m.unknown?'≤ ':''}${money(available)}</div><p class="muted small">Teto total de US$ 5, incluindo os gastos históricos do Hermes. A abrangência do teto ainda depende de esclarecimento.</p><div class="allocation"><div style="width:${Math.min(100,historical/5*100)}%;background:#6a8060" title="Histórico conhecido"></div><div style="width:${Math.min(100,m.spent/5*100)}%;background:#25493d" title="Novos gastos"></div><div style="width:${Math.min(100,(oldReserve+m.reserved)/5*100)}%;background:#d5b269" title="Reservas"></div></div><div class="legend"><span><i style="background:#6a8060"></i>Histórico</span><span><i style="background:#25493d"></i>Novos gastos</span><span><i style="background:#d5b269"></i>Reservas</span><span><i style="background:#e3e8db"></i>Disponível</span></div><div style="margin-top:20px">${[['Histórico conhecido',historical],['Reserva histórica de timeout',oldReserve],['Novos custos conhecidos',m.spent],['Novas reservas pendentes',m.reserved]].map(([t,n])=>`<div class="money-row"><span>${t}</span><strong>${money(n,9)}</strong></div>`).join('')}</div>${m.unknown?`<div class="error-box">${m.unknown} tentativa(s) sem custo conhecido. O saldo mostrado é um limite superior; as reservas podem não cobrir toda cobrança futura.</div>`:''}${available<0?'<div class="error-box">Os valores registrados ultrapassam o teto. Suspender novas chamadas e reconciliar o ledger.</div>':''}</div></div><div class="panel"><div class="panel-head"><h2>Cotas previstas no plano</h2><span class="badge">Não são gastos</span></div><div class="panel-body cost-list">${PLAN.budget.map(b=>`<div class="money-row"><span>${esc(b.stage)}</span><strong>${money(b.cap_usd,2)}</strong></div>`).join('')}<div class="money-row"><strong>Total planejado</strong><strong>${money(1.70,2)}</strong></div><p class="small muted" style="margin-top:14px">Atribuição de consumo a cada cota exige o ledger de execução. O painel mostra os custos observados por sistema abaixo.</p></div></div></div>
 <div class="panel"><div class="panel-head"><h2>Novos custos por sistema</h2><span class="small muted">Sem misturar o histórico</span></div>${state.runs.length?`<div class="table-wrap"><table><thead><tr><th>Sistema</th><th>Tentativas</th><th>Conhecido</th><th>Reservado</th><th>Custo ausente</th></tr></thead><tbody>${PLAN.systems.filter(s=>state.runs.some(r=>r.system_id===s.id)).map(s=>{const a=state.runs.filter(r=>r.system_id===s.id).flatMap(r=>r.attempts);return `<tr><td>${esc(s.name)}</td><td>${a.length}</td><td>${money(a.reduce((n,x)=>n+(x.cost_usd||0),0))}</td><td>${money(a.reduce((n,x)=>n+(x.reserved_usd||0),0))}</td><td>${a.filter(x=>x.cost_usd===null).length}</td></tr>`}).join('')}</tbody></table></div>`:empty('Sem custos novos registrados','Os custos aparecerão quando forem importados com as tentativas.')}</div>
 <div class="hint">A chave atual informou limite de US$ 50 e uso zero na consulta histórica de metadados. Limite de chave não é saldo de créditos e não amplia a autorização de US$ 5. Consulte o plano para o procedimento TypeSafe/OpenRouter.</div>`;
}
function artifactURL(key){const files={pdf:'output/pdf/PLANO-CIENTIFICO-JEV-HELENA.pdf',plan:'docs/PLANO-CIENTIFICO-JEV-HELENA.md',matrix:'planning/matriz-testes.csv',sources:'research/FONTES.md',schema:'planning/schema.sql',audit:'research/hermes/auditoria-local.json',historical:'research/hermes/fase2-decisoes-do-pdf.csv',guide:'lab/README.md'};return location.protocol.startsWith('http')?'/artifacts/'+key:'../'+files[key]}
function filesView(){const docs=[['pdf','PDF','Plano científico','Documento completo com método, orçamento e fichas dos 15 sistemas.'],['plan','MD','Plano editável','Fonte de leitura em Markdown.'],['matrix','CSV','Matriz dos sistemas','Perguntas, comparadores, amostras e critérios.'],['sources','REF','Fontes e revisões','Repositórios e commits estudados.'],['audit','JSON','Auditoria local do Hermes','Cálculos reproduzidos a partir das tabelas do PDF.'],['historical','CSV','96 decisões históricas','Tabela transcrita com a página de origem.'],['schema','SQL','Contrato do laboratório','Estrutura prevista para o registro detalhado.'],['guide','GUIA','Como alimentar o painel','Formato de importação, servidor e atualização dos dados.']];
 return intro('DOCUMENTAÇÃO / PROVENIÊNCIA','Volte à fonte.','O plano, as evidências e os contratos de dados ficam acessíveis no mesmo lugar.')+`<div class="doc-grid">${docs.map(([key,type,title,description])=>`<a class="doc-card" href="${artifactURL(key)}" target="_blank" rel="noopener"><span class="doc-icon">${type}</span><div><h3>${title} ↗</h3><p>${description}</p></div></a>`).join('')}</div><div class="hint">Referências anteriores ajudam a desenhar os próximos testes. <button class="text-link" id="historicalMetrics">Consultar métricas históricas</button> · <button class="text-link" data-history>Consultar decisões históricas</button></div><div class="panel" style="margin-top:23px"><div class="panel-head"><h2>Portabilidade dos dados</h2></div><div class="panel-body"><p class="muted">No modo conectado, alterações são gravadas na pasta do projeto e a tela acompanha novas revisões. No arquivo HTML aberto diretamente, o acompanhamento fica neste navegador.</p><div class="dialog-actions"><button class="button dark" data-backup>Exportar backup completo</button><button class="button" data-import>Importar resultados ou backup</button></div><p class="small muted">Um backup inclui status, notas e execuções. Chaves de API não são lidas nem incluídas.</p></div></div>`;
}
function render(){
 const focus=document.activeElement,focusId=focus?.id,start=focus?.selectionStart,end=focus?.selectionEnd;
 $('#content').innerHTML=({overview:terminalView,execution,systems:systemsView,results:resultsView,metrics:metricsView,budget:budgetView,files:filesView}[activeView])();
 $('#crumb').textContent=TITLES[activeView];document.querySelectorAll('[data-view]').forEach(b=>{if(b.dataset.view===activeView)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});
 bindView();if(activeView==='metrics')bindMetrics();connection();
 if(focusId&&$('#'+focusId)){const el=$('#'+focusId);el.focus({preventScroll:true});if(typeof start==='number'&&el.setSelectionRange)try{el.setSelectionRange(start,end)}catch{}}
}
function navigate(view){if(!TITLES[view])view='overview';activeView=view;location.hash=view;render();window.scrollTo({top:0,behavior:'instant'})}
function bindView(){
 if($('#terminalFilter'))$('#terminalFilter').onchange=()=>{terminalFilter=$('#terminalFilter').value;render()};
 if($('#historicalMetrics'))$('#historicalMetrics').onclick=()=>{metricFilter.source='history';metricFilter.task='evidence';metricFilter.format='solo';metricFilter.split='holdout';navigate('metrics')};
 document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{if(b.dataset.go==='metrics')metricFilter.source='new';if(b.dataset.go==='results')filters.source='new';navigate(b.dataset.go)});
 document.querySelectorAll('[data-import]').forEach(b=>b.onclick=openImport);
 document.querySelectorAll('[data-history]').forEach(b=>b.onclick=()=>{filters.source='history';filters.resultSystem='';filters.resultSplit='';filters.resultMode='';pageNumber=1;navigate('results')});
 document.querySelectorAll('[data-backup]').forEach(b=>b.onclick=backup);
 document.querySelectorAll('[data-system]').forEach(b=>b.onclick=()=>showSystem(b.dataset.system));
 document.querySelectorAll('[data-run]').forEach(b=>b.onclick=()=>showRun(b.dataset.run));
 document.querySelectorAll('[data-phase]').forEach(b=>b.onclick=()=>{filters.executionPhase=b.dataset.phase;render()});
 document.querySelectorAll('[data-source]').forEach(b=>b.onclick=()=>{filters.source=b.dataset.source;filters.resultMode='';filters.resultSplit='';filters.resultSystem='';filters.resultSearch='';filters.resultCorrect='';pageNumber=1;render()});
 document.querySelectorAll('[data-progress]').forEach(el=>el.onchange=async()=>{const next=structuredClone(state),id=el.dataset.progress;next.system_progress[id]={...(next.system_progress[id]||{}),[filters.executionPhase]:el.value,updated_at:new Date().toISOString()};event(next,`${system(id).name}: ${PHASES[filters.executionPhase]} → ${LABELS[el.value]}.`,'manual');await save(next);render()});
 document.querySelectorAll('[data-stage]').forEach(el=>el.onchange=async()=>{const next=structuredClone(state);next.stage_progress[el.dataset.stage]={status:el.value,updated_at:new Date().toISOString()};event(next,`Etapa ${el.dataset.stage}: ${STAGES[el.dataset.stage][0]} → ${LABELS[el.value]}.`,'manual');await save(next);render()});
 for(const [id,key] of Object.entries({systemSearch:'systemSearch',familyFilter:'family',executionStatus:'executionStatus',resultSearch:'resultSearch',resultSystem:'resultSystem',resultCorrect:'resultCorrect',resultSplit:'resultSplit',resultMode:'resultMode'})){const el=$('#'+id);if(el)el.addEventListener(el.tagName==='INPUT'?'input':'change',()=>{filters[key]=el.value;pageNumber=1;render()})}
 if($('#exportProgress'))$('#exportProgress').onclick=()=>downloadCSV('jev-acompanhamento.csv',PLAN.systems.map(s=>({id:s.id,sistema:s.name,simples:LABELS[progress(s.id,'simple')],aprofundamento:LABELS[progress(s.id,'deep')],notas:state.system_progress[s.id]?.notes||'',execucoes:state.runs.filter(r=>r.system_id===s.id).length})));
 if($('#exportDecisions'))$('#exportDecisions').onclick=()=>downloadCSV('jev-decisoes-'+filters.source+'.csv',resultRows());
 if($('#prevPage'))$('#prevPage').onclick=()=>{pageNumber--;render()};if($('#nextPage'))$('#nextPage').onclick=()=>{pageNumber++;render()};
}
function showSystem(id){const s=system(id),p=state.system_progress[id]||{};
 $('#systemDetail').innerHTML=`<span class="eyebrow">${s.id} / ${esc(s.family)}</span><h2 style="margin-top:12px">${esc(s.name)}</h2><p class="muted">${esc(s.question)}</p><div class="detail-section"><h3>Rodada simples · ${s.smoke_units} ${esc(s.smoke_unit)}</h3><p>${esc(s.smoke)}</p><p style="margin-top:9px" class="small muted">Até ${s.smoke_jev_call_cap} tentativas Jev + ${s.smoke_llm_call_cap} auxiliares.</p></div>${[['Aprofundamento',s.deep],['Comparador',s.baseline],['Critério proposto',s.gate],['Preparação e dependências',s.dependencies]].map(([t,d])=>`<div class="detail-section"><h3>${t}</h3><p>${esc(d)}</p></div>`).join('')}<div class="detail-section"><h3>Acompanhamento</h3><form id="systemForm"><div class="form-grid"><label class="form-field">Rodada simples<select name="simple">${optionsStatus(p.simple||'planned')}</select></label><label class="form-field">Aprofundamento<select name="deep">${optionsStatus(p.deep||'planned')}</select></label></div><label class="form-field">Notas, bloqueios e próximo passo<textarea name="notes" maxlength="6000" placeholder="Registre o que falta, a evidência encontrada ou uma decisão de execução.">${esc(p.notes||'')}</textarea></label><div class="dialog-actions"><a href="${s.url}/tree/${s.sha}" target="_blank" rel="noreferrer" class="small">Código estudado · ${s.sha.slice(0,10)} ↗</a><button class="button dark" type="submit">Salvar acompanhamento</button></div><p class="small muted">Status manual não altera métricas nem comprova que o sistema foi testado.</p></form></div>`;
 $('#systemForm').onsubmit=async e=>{e.preventDefault();const values=new FormData(e.target),next=structuredClone(state);next.system_progress[id]={simple:values.get('simple'),deep:values.get('deep'),notes:values.get('notes'),updated_at:new Date().toISOString()};event(next,'Acompanhamento atualizado: '+s.name+'.','manual');if(await save(next)){$('#systemDialog').close();render();toast('Acompanhamento salvo.')}};
 $('#systemDialog').showModal();
}
function safeLink(url){try{const u=new URL(url,location.href);return ['http:','https:'].includes(u.protocol)?u.href:null}catch{return null}}
function showRun(id){const r=state.runs.find(r=>r.id===id);if(!r)return;const times=r.attempts.filter(a=>a.status==='success'&&!a.cache_hit&&a.latency_ms!==null).map(a=>a.latency_ms).sort((a,b)=>a-b),median=times.length?(times[Math.floor((times.length-1)/2)]+times[Math.ceil((times.length-1)/2)])/2:null;
 $('#runDetail').innerHTML=`<h2>${esc(r.id)}</h2><p class="muted">${esc(system(r.system_id).name)} · ${PHASES[r.phase]} · ${EVIDENCE[r.evidence]}</p><div class="result-summary"><div><strong>${r.attempts.length}</strong><span>tentativas</span></div><div><strong>${r.decisions.length}</strong><span>decisões</span></div><div><strong>${money(r.attempts.reduce((n,a)=>n+(a.cost_usd||0),0))}</strong><span>custo conhecido</span></div><div><strong>${median===null?'—':number(median)+' ms'}</strong><span>mediana informada · ${times.length} sucessos sem cache</span></div></div><div class="detail-section"><h3>Proveniência</h3><p>Modelo: ${esc(r.model||'Não informado')}<br>Provedor: ${esc(r.provider||'Não informado')}<br>Conjunto: ${esc(r.dataset||'Não informado')}<br>Início: ${date(r.started_at)} · ${esc(LABELS[r.status])}</p></div><div class="detail-section"><h3>Observações</h3><p style="white-space:pre-wrap">${esc(r.notes||'Sem observações registradas.')}</p></div>${r.artifacts?.length?`<div class="detail-section"><h3>Artefatos de evidência</h3>${r.artifacts.map(a=>safeLink(a.url)?`<p><a href="${esc(safeLink(a.url))}" target="_blank" rel="noreferrer">${esc(a.label)}</a></p>`:`<p>${esc(a.label)}: ${esc(a.url)}</p>`).join('')}</div>`:''}<details><summary class="small">Inspecionar registro completo</summary><pre class="code-block">${esc(JSON.stringify(r,null,2))}</pre></details><div class="dialog-actions"><button id="exportRun" class="button">↓ Exportar esta execução</button></div>`;
 $('#exportRun').onclick=()=>downloadJSON('jev-'+r.id+'.json',{schema_version:1,kind:'jev-lab-results',runs:[r]});$('#runDialog').showModal();
}
function event(next,text,kind){next.events.push({at:new Date().toISOString(),text,kind});next.events=next.events.slice(-500)}
async function save(next){
 if(saving){toast('Aguarde a gravação atual.');return false}if(locked||mode==='disconnected'||mode==='loading'){toast('Armazenamento indisponível. Exporte um backup e atualize a conexão.');return false}
 saving=true;try{
  next.updated_at=new Date().toISOString();validateState(next);
  if(mode==='api'){
   const response=await fetch('/api/state',{method:'PUT',headers:{'Content-Type':'application/json','X-Jev-Lab':'1'},body:JSON.stringify(next)});
   if(response.status===409){await loadServer();throw Error('Outra atualização chegou antes. Os dados foram recarregados; confira e salve novamente.')}
   if(!response.ok)throw Error((await response.json()).error||'Não foi possível salvar.');state=await response.json();
  }else{const stored=localStorage.getItem(STORE);if(stored){const current=JSON.parse(stored);validateState(current);if(current.revision!==state.revision){state=current;throw Error('Outra aba alterou os dados. Confira a revisão atual antes de salvar novamente.')}}next.revision=state.revision+1;localStorage.setItem(STORE,JSON.stringify(next));state=next}
  connection();return true;
 }catch(e){toast(e.message);return false}finally{saving=false}
}
async function loadServer(){const response=await fetch('/api/state',{cache:'no-store',signal:AbortSignal.timeout(5000)});if(!response.ok)throw Error('Servidor indisponível');const next=await response.json();validateState(next);const changed=next.revision!==state.revision||next.updated_at!==state.updated_at;state=next;mode='api';locked=false;notice('');connection();if(changed&&!document.querySelector('dialog[open]'))render()}
async function initialize(){
 if(location.protocol.startsWith('http')){try{await loadServer()}catch{mode='disconnected';notice('Não foi possível carregar os dados da pasta. A tela mostra o retrato incluído no HTML; alterações estão bloqueadas até a conexão voltar.')}}
 else{mode='local';try{const raw=localStorage.getItem(STORE);if(raw){const parsed=JSON.parse(raw);validateState(parsed);state=parsed}}catch{locked=true;notice('O armazenamento local não pôde ser lido com segurança. Os dados existentes foram preservados. Use o modo conectado ou recupere um backup antes de editar.')}}
 activeView=TITLES[location.hash.slice(1)]?location.hash.slice(1):'overview';render();
}
function assert(condition,message){if(!condition)throw Error(message)}
function object(v){return v!==null&&typeof v==='object'&&!Array.isArray(v)}
function textField(v,name,limit=6000){assert(typeof v==='string'&&v.length<=limit,'Campo inválido: '+name)}
function numField(v,name,nullable=false){assert((nullable&&v===null)||(typeof v==='number'&&Number.isFinite(v)&&v>=0),'Número inválido: '+name)}
function onlyKeys(o,keys,name){assert(object(o),'Objeto inválido: '+name);for(const k of Object.keys(o))assert(keys.includes(k),'Campo não reconhecido em '+name+': '+k)}
function validateRun(r){
 onlyKeys(r,['id','system_id','phase','evidence','status','started_at','finished_at','provider','model','dataset','notes','attempts','decisions','artifacts'],'execução');
 textField(r.id,'id',160);assert(r.id.trim().length>0,'ID vazio');assert(system(r.system_id),'Sistema desconhecido');assert(PHASES[r.phase],'Rodada inválida');assert(EVIDENCE[r.evidence],'Evidência inválida');assert(['running','completed','failed'].includes(r.status),'Status de execução inválido');
 assert(typeof r.started_at==='string'&&Number.isFinite(Date.parse(r.started_at)),'Data inicial inválida');if(r.finished_at!=null)assert(typeof r.finished_at==='string'&&Number.isFinite(Date.parse(r.finished_at)),'Data final inválida');
 for(const k of ['provider','model','dataset','notes'])if(r[k]!==undefined)textField(r[k],k);
 assert(Array.isArray(r.attempts)&&Array.isArray(r.decisions),'Execução precisa de attempts e decisions');assert(r.attempts.length<=10000&&r.decisions.length<=50000,'Pacote excede o limite de registros');
 const ids=new Set();for(const a of r.attempts){onlyKeys(a,['id','status','latency_ms','input_tokens','output_tokens','cost_usd','reserved_usd','cache_hit','error'],'tentativa');textField(a.id,'attempt.id',160);assert(a.id.length>0&&!ids.has(a.id),'ID de tentativa vazio ou duplicado');ids.add(a.id);assert(['success','timeout','error','pending'].includes(a.status),'Status de tentativa inválido');numField(a.cost_usd,'cost_usd',true);numField(a.reserved_usd,'reserved_usd');numField(a.latency_ms,'latency_ms',true);for(const k of ['input_tokens','output_tokens']){numField(a[k],k,true);assert(a[k]===null||Number.isInteger(a[k]),'Tokens devem ser inteiros')}assert(typeof a.cache_hit==='boolean','cache_hit deve ser booleano');if(a.error!==undefined)textField(a.error,'error')}
 const decisions=new Set();for(const d of r.decisions){onlyKeys(d,['id','case_id','attempt_id','task','split','expected','predicted','correct','confidence','question_id','group_id'],'decisão');for(const k of ['id','case_id','attempt_id','task','split'])textField(d[k],k,250);assert(d.id.length>0&&!decisions.has(d.id),'ID de decisão vazio ou duplicado');decisions.add(d.id);assert(ids.has(d.attempt_id),'Decisão aponta para tentativa ausente');assert(['pilot','development','calibration','test','diagnostic'].includes(d.split),'Partição inválida');for(const k of ['expected','predicted'])assert(d[k]===null||typeof d[k]==='string','Saída deve ser texto ou null');assert(d.correct===null||typeof d.correct==='boolean','correct deve ser booleano ou null');numField(d.confidence,'confidence',true);assert(d.confidence===null||d.confidence<=1,'confidence fora de [0,1]');for(const k of ['question_id','group_id'])if(d[k]!==undefined)textField(d[k],k,250)}
 if(r.artifacts!==undefined){assert(Array.isArray(r.artifacts)&&r.artifacts.length<=100,'Artefatos inválidos');for(const a of r.artifacts){onlyKeys(a,['label','url'],'artefato');textField(a.label,'label',250);textField(a.url,'url',2000)}}
}
function validateState(s){
 onlyKeys(s,['schema_version','revision','updated_at','system_progress','stage_progress','runs','events'],'estado');assert(s.schema_version===1,'Versão de formato não suportada');assert(Number.isInteger(s.revision)&&s.revision>=0,'Revisão inválida');assert(typeof s.updated_at==='string'&&Number.isFinite(Date.parse(s.updated_at)),'Data de atualização inválida');assert(object(s.system_progress)&&object(s.stage_progress),'Acompanhamento inválido');assert(Array.isArray(s.runs)&&s.runs.length<=2000,'Lista de execuções inválida');assert(Array.isArray(s.events)&&s.events.length<=500,'Lista de eventos inválida');
 for(const [id,p] of Object.entries(s.system_progress)){assert(system(id),'Sistema desconhecido no acompanhamento');onlyKeys(p,['simple','deep','notes','updated_at'],'acompanhamento');for(const k of ['simple','deep'])if(p[k]!==undefined)assert(['planned','running','done','blocked','paused'].includes(p[k]),'Status inválido');if(p.notes!==undefined)textField(p.notes,'notes');if(p.updated_at!==undefined)textField(p.updated_at,'updated_at',80)}
 for(const [id,p] of Object.entries(s.stage_progress)){assert(/^[1-8]$/.test(id),'Etapa inválida');onlyKeys(p,['status','updated_at'],'etapa');assert(['planned','running','done','blocked','paused'].includes(p.status),'Status de etapa inválido')}
 const ids=new Set(),attemptIds=new Set();for(const r of s.runs){validateRun(r);assert(!ids.has(r.id),'Execução duplicada');ids.add(r.id);for(const a of r.attempts){assert(!attemptIds.has(a.id),'ID de tentativa repetido em execuções diferentes; isso duplicaria os custos');attemptIds.add(a.id)}}
 for(const e of s.events){onlyKeys(e,['at','text','kind'],'evento');textField(e.at,'at',80);textField(e.text,'text',1200);assert(['manual','import','evidence'].includes(e.kind),'Tipo de evento inválido')}
 assert(!/sk-or-v1-[a-zA-Z0-9]{20,}|"(?:api[_-]?key|authorization|secret|password)"\s*:/i.test(JSON.stringify(s)),'O pacote parece conter uma credencial. Remova segredos antes de importar.');
}
function openImport(){pendingImport=null;$('#importFile').value='';$('#importPreview').replaceChildren();$('#confirmImport').disabled=true;$('#importDialog').showModal()}
function prepareImport(payload){
 let incoming,backupState=null;
 if(payload.kind==='jev-lab-backup'){onlyKeys(payload,['kind','schema_version','exported_at','state'],'backup');validateState(payload.state);incoming=payload.state.runs;backupState=payload.state}
 else{onlyKeys(payload,['schema_version','kind','runs'],'pacote');assert(payload.schema_version===1&&payload.kind==='jev-lab-results','Use o formato jev-lab-results, versão 1');assert(Array.isArray(payload.runs),'Campo runs ausente');incoming=payload.runs;incoming.forEach(validateRun)}
 const next=structuredClone(state);let added=0,duplicate=0,updated=0;
 for(const r of incoming){const index=next.runs.findIndex(x=>x.id===r.id);if(index>=0){const existing=next.runs[index];if(stable(existing)===stable(r)){duplicate++}else{assertRunUpdate(existing,r);next.runs[index]=r;updated++}}else{next.runs.push(r);added++}}
 if(backupState){next.system_progress={...next.system_progress,...backupState.system_progress};next.stage_progress={...next.stage_progress,...backupState.stage_progress};next.events=[...new Map([...backupState.events,...next.events].map(e=>[stable(e),e])).values()].sort((a,b)=>Date.parse(a.at)-Date.parse(b.at)).slice(-500)}
 validateState(next);return {next,added,duplicate,updated,backup:!!backupState};
}
function assertRunUpdate(old,next){
 for(const key of ['id','system_id','phase','evidence','started_at','provider','model','dataset','finished_at'])if(old[key]!=null&&old[key]!=='')assert(old[key]===next[key],'Atualização alteraria a identidade/proveniência da execução: '+old.id);
 if(old.status!=='running')assert(next.status===old.status,'Não é permitido reescrever o desfecho de uma execução encerrada');
 const attempts=new Map(next.attempts.map(a=>[a.id,a]));for(const prior of old.attempts){const current=attempts.get(prior.id);assert(current,'Atualização removeria uma tentativa já registrada');for(const [key,value] of Object.entries(prior)){if(key==='reserved_usd')continue;if(key==='status'&&value==='pending')continue;if(value===null&&['cost_usd','latency_ms','input_tokens','output_tokens'].includes(key))continue;assert(stable(value)===stable(current[key]),'Atualização alteraria um valor já conhecido da tentativa '+prior.id)}}
 const decisions=new Map(next.decisions.map(d=>[d.id,d]));for(const prior of old.decisions)assert(stable(prior)===stable(decisions.get(prior.id)),'Atualização removeria ou alteraria uma decisão já registrada');
}
$('#importFile').onchange=async e=>{pendingImport=null;$('#confirmImport').disabled=true;try{const f=e.target.files[0];if(!f)return;assert(f.size<=8*1024*1024,'Arquivo maior que 8 MB');const raw=await f.text();assert(!/sk-or-v1-[a-zA-Z0-9]{20,}|"(?:api[_-]?key|authorization|secret|password)"\s*:/i.test(raw),'O arquivo contém indício de credencial.');const payload=JSON.parse(raw);pendingImport={payload,...prepareImport(payload)};$('#importPreview').innerHTML=`<div class="success-box"><strong>${pendingImport.added} execuções novas</strong> · ${pendingImport.updated} atualizadas · ${pendingImport.duplicate} já existentes.${pendingImport.backup?'<p style="margin-top:10px;margin-bottom:0">Backup: status e notas presentes nele substituirão os mesmos campos do acompanhamento atual. Execuções atuais serão preservadas.</p>':''}</div>`;$('#confirmImport').disabled=false}catch(err){$('#importPreview').innerHTML=`<div class="error-box">${esc(err.message)}</div>`}};
$('#confirmImport').onclick=async()=>{if(!pendingImport)return;try{const prepared=prepareImport(pendingImport.payload);event(prepared.next,`Pacote importado: ${prepared.added} execuções novas; ${prepared.updated} atualizadas; ${prepared.duplicate} duplicadas ignoradas${prepared.backup?'; acompanhamento recuperado de backup':''}.`,'import');if(await save(prepared.next)){$('#importDialog').close();pendingImport=null;render();toast('Dados importados e salvos.')}}catch(e){$('#importPreview').innerHTML=`<div class="error-box">${esc(e.message)}</div>`}};
function download(name,content,type){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([content],{type}));a.href=url;a.download=name.replace(/[^\p{L}\p{N}._-]/gu,'-');document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2000)}
function downloadJSON(name,value){download(name,JSON.stringify(value,null,2),'application/json')}
function downloadCSV(name,rows){if(!rows.length)return;const keys=[...new Set(rows.flatMap(Object.keys))],cell=v=>{let x=v==null?'':typeof v==='object'?JSON.stringify(v):String(v);if(/^[=+@\-\t\r]/.test(x))x="'"+x;return '"'+x.replaceAll('"','""')+'"'};download(name,'\ufeff'+[keys.map(cell).join(','),...rows.map(r=>keys.map(k=>cell(r[k])).join(','))].join('\r\n'),'text/csv;charset=utf-8')}
function backup(){downloadJSON('jev-backup-'+new Date().toISOString().slice(0,10)+'.json',{schema_version:1,kind:'jev-lab-backup',exported_at:new Date().toISOString(),state})}
$('#templateButton').onclick=()=>downloadJSON('jev-resultados-vazio.json',{schema_version:1,kind:'jev-lab-results',runs:[]});
$('#backupButton').onclick=backup;$('#importButton').onclick=openImport;
$('#refreshButton').onclick=async()=>{if(location.protocol.startsWith('http')){try{await loadServer();render();toast('Dados da pasta atualizados.')}catch{mode='disconnected';connection();notice('Conexão interrompida. Os dados exibidos foram preservados; tente atualizar novamente.')}}else{toast('Arquivo local: importe um pacote para acrescentar dados.');render()}};
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{if(b.dataset.view==='metrics')metricFilter.source='new';if(b.dataset.view==='results')filters.source='new';navigate(b.dataset.view)});
window.addEventListener('hashchange',()=>{const view=location.hash.slice(1);if(TITLES[view]&&activeView!==view){activeView=view;render()}});
window.addEventListener('storage',e=>{if(mode==='local'&&e.key===STORE&&e.newValue){try{const next=JSON.parse(e.newValue);validateState(next);if(!document.querySelector('dialog[open]')){state=next;render()}else toast('Dados alterados em outra aba. Feche a ficha e atualize antes de salvar.')}catch{notice('Outra aba gravou dados inválidos. Seu estado atual foi preservado.')}}});
setInterval(async()=>{if(location.protocol.startsWith('http')&&!saving&&!document.hidden&&!document.querySelector('dialog[open]')){try{await loadServer()}catch{if(mode!=='disconnected'){mode='disconnected';connection();notice('Conexão interrompida. Exibindo o último estado recebido; alterações estão bloqueadas.')}}}},5000);
initialize();
