/* Metrics calculated only from the selected real records. No generated examples. */
const metricFilter={source:'new',task:'',format:'solo',split:'',run:'',label:''};
const TASK_NAMES={triage:'Triagem de pedidos',evidence:'Seleção de evidências',claim:'Afirmação versus evidência'};
const CLASS_NAMES={relevant:'Relevante',irrelevant:'Irrelevante',supported:'Sustentada',contradicted:'Contradita',insufficient:'Informação insuficiente',comunicacao:'Comunicação',juridico:'Jurídico',organizacao:'Organização',financeiro:'Financeiro',engenharia:'Engenharia',pesquisa:'Pesquisa',outro:'Outro'};
function className(x){return CLASS_NAMES[x]||x}
function percent(x){return x===null?'—':(x*100).toLocaleString('pt-BR',{maximumFractionDigits:1})+'%'}
function wilsonInterval(k,n){if(!n)return null;const z=1.959963984540054,p=k/n,denom=1+z*z/n,centre=(p+z*z/(2*n))/denom,half=z*Math.sqrt(p*(1-p)/n+z*z/(4*n*n))/denom;return [Math.max(0,centre-half),Math.min(1,centre+half)]}
function quantileNearest(values,q){if(!values.length)return null;const sorted=[...values].sort((a,b)=>a-b);return sorted[Math.max(0,Math.ceil(q*sorted.length)-1)]}
function medianValue(values){if(!values.length)return null;const sorted=[...values].sort((a,b)=>a-b),m=Math.floor(sorted.length/2);return sorted.length%2?sorted[m]:(sorted[m-1]+sorted[m])/2}
function classificationStats(rows){
 const graded=rows.filter(r=>r.correct!==null), correct=graded.filter(r=>r.correct).length;
 const labeled=rows.filter(r=>r.expected!==null&&r.predicted!==null);
 const labels=[...new Set(labeled.flatMap(r=>[r.expected,r.predicted]))].sort();
 const byClass=Object.fromEntries(labels.map(label=>{const tp=labeled.filter(r=>r.expected===label&&r.predicted===label).length,fp=labeled.filter(r=>r.expected!==label&&r.predicted===label).length,fn=labeled.filter(r=>r.expected===label&&r.predicted!==label).length;return [label,{tp,fp,fn,support:tp+fn,precision:tp+fp?tp/(tp+fp):null,recall:tp+fn?tp/(tp+fn):null,f1:2*tp+fp+fn?2*tp/(2*tp+fp+fn):null}]}));
 const uniqueCases=new Set(rows.map(r=>r.case_id)).size;
 const groups=rows.map(r=>r.group_id||r.case_id),uniqueGroups=new Set(groups).size;
 return {graded,correct,labeled,labels,byClass,accuracy:graded.length?correct/graded.length:null,
  macroF1:labels.length?labels.reduce((n,l)=>n+(byClass[l].f1||0),0)/labels.length:null,
  uniqueCases,uniqueGroups,repeated:uniqueCases<rows.length||uniqueGroups<rows.length,
  correlatedBatch:rows.every(r=>r.attempt_id)&&new Set(rows.map(r=>r.attempt_id)).size<rows.length,
  inconsistent:labeled.some(r=>r.correct!==null&&r.correct!==(r.expected===r.predicted))};
}
function metricSelection(){
 if(metricFilter.source==='history')return {rows:HISTORY.filter(r=>r.app===metricFilter.task&&r.mode===metricFilter.format&&(!metricFilter.split||r.split===metricFilter.split)).map(r=>({case_id:r.case_id,attempt_id:'pdf:'+r.call_id,task:r.app,split:r.split,expected:r.expected,predicted:r.predicted,correct:Number(r.correct)===1,confidence:Number(r.confidence_pdf)})),run:null};
 if(!metricFilter.run&&state.runs.length)metricFilter.run=state.runs[state.runs.length-1].id;
 const run=state.runs.find(r=>r.id===metricFilter.run);if(!run)return {rows:[],run:null};
 const tasks=[...new Set(run.decisions.map(d=>d.task))];if(!tasks.includes(metricFilter.task))metricFilter.task=tasks[0]||'';
 return {rows:run.decisions.filter(d=>d.task===metricFilter.task&&(!metricFilter.split||d.split===metricFilter.split)),run};
}
function metricCard(name,value,meaning,reading,formula,tag=''){return `<article class="metric-card"><div class="metric-title">${esc(name)}${tag?`<span class="badge">${esc(tag)}</span>`:''}</div><strong class="metric-value">${esc(value)}</strong><p>${meaning}</p><div class="metric-reading">${reading}</div><details class="metric-help"><summary>Como calculamos</summary><p>${formula}</p></details></article>`}
function metricsView(){
 const historical=metricFilter.source==='history';if(historical&&!TASK_NAMES[metricFilter.task])metricFilter.task='triage';const selection=metricSelection(),rows=selection.rows,run=selection.run,s=classificationStats(rows);
 if(!s.labels.includes(metricFilter.label))metricFilter.label=s.labels.includes('relevant')?'relevant':s.labels[0]||'';
 const c=s.byClass[metricFilter.label],dependent=s.repeated||s.correlatedBatch,interval=!dependent?wilsonInterval(s.correct,s.graded.length):null;
 const tasks=historical?TASK_NAMES:Object.fromEntries([...new Set((run?.decisions||[]).map(d=>d.task))].map(t=>[t,TASK_NAMES[t]||t]));
 const title=historical?'Referência histórica de comparação.':'Métricas dos novos testes.';
 const stageOptions=historical?{holdout:'Reservado para avaliação',development:'Desenvolvimento'}:{test:'Teste final',development:'Desenvolvimento',calibration:'Calibração',pilot:'Piloto',diagnostic:'Diagnóstico'};
 const formatter=historical?`<label>Formato<select id="metricFormat">${opts({solo:'Individual',batch:'Lote'},metricFilter.format)}</select></label>`:`<label>Execução<select id="metricRun">${opts(Object.fromEntries(state.runs.map(r=>[r.id,r.id+' / '+r.system_id])),metricFilter.run,'Escolha uma execução')}</select></label>`;
 return intro('ESTATÍSTICA / EM LINGUAGEM SIMPLES',title,'Cada número vem com sua pergunta, explicação e limite. Comece pelo tamanho da amostra: um bom percentual com poucos casos ainda deixa muita dúvida.')+
 `<div class="section-tabs"><button data-metric-source="new" class="${!historical?'active':''}">Novos testes</button><button data-metric-source="history" class="${historical?'active':''}">Histórico de referência</button></div><div class="filters">${formatter}<label>Tarefa<select id="metricTask">${opts(tasks,metricFilter.task)}</select></label><label>Partição<select id="metricSplit">${opts(stageOptions,metricFilter.split,'Todas · exploração')}</select></label><label>Classe em destaque<select id="metricLabel">${opts(Object.fromEntries(s.labels.map(l=>[l,className(l)])),metricFilter.label)}</select></label></div>
 <p class="small muted">A classe em destaque muda precisão, recall e F1 da classe. Acurácia e macro-F1 continuam considerando todas as classes do recorte.</p>
 ${!rows.length?`<div class="panel">${empty('Ainda não há dados neste recorte',historical?'Selecione outra combinação de filtros.':'Selecione uma execução importada com decisões. As explicações abaixo continuam disponíveis.')}</div>`:`<div class="metric-context"><span class="eyebrow">RECORTE ATUAL</span><p><strong>${rows.length} decisões · ${s.uniqueCases} casos distintos</strong> · ${historical?'tabelas do PDF, fase 2':esc(run.id)}</p><span>${s.graded.length} decisões têm avaliação de acerto. ${historical?'Os casos são sintéticos e escolhidos pelos autores.':''} ${metricFilter.split===''?'Desenvolvimento e avaliação podem estar misturados: use como exploração.':''}</span></div>`}
 ${dependent?'<div class="hint">Há repetição de casos/grupos ou várias decisões na mesma tentativa. O intervalo simples de acurácia foi desativado: ignorar essa dependência daria uma falsa impressão de certeza.</div>':''}
 ${s.inconsistent?'<div class="hint">O campo de acerto usa um critério diferente da igualdade entre rótulos em parte dos registros. Acurácia usa o acerto informado; precisão, recall e F1 usam os rótulos. Investigue antes de compará-los.</div>':''}
 <div class="metric-grid">
 ${metricCard('Acurácia',percent(s.accuracy),'De todas as decisões avaliadas, <strong>quantas estavam certas?</strong>',s.graded.length?`${s.correct} acertos em ${s.graded.length} decisões. ${s.graded.length-s.correct} erro(s).`:'Sem decisões com gabarito neste recorte.','Acertos ÷ decisões com gabarito. As decisões sem gabarito não entram na conta. Ela pode esconder uma classe rara que o modelo nunca acerta.')}
 ${metricCard('Intervalo de confiança de 95%',interval?percent(interval[0])+' a '+percent(interval[1]):'Não calculado','Mostra <strong>quanta incerteza a amostra ainda deixa</strong> sobre a taxa de acerto.',interval?`Mesmo com ${percent(s.accuracy)} observado, a faixa vai até ${percent(interval[0])} no limite inferior. ${s.graded.length<30?'Poucos casos: trate como sinal inicial.':'A faixa ainda depende da representatividade dos casos.'}`:dependent?'Casos relacionados precisam de análise por grupos.':'Faltam decisões avaliadas.','Intervalo de Wilson. Se repetíssemos o procedimento muitas vezes com amostras independentes e representativas, aproximadamente 95% das faixas conteriam a taxa real. Não é uma chance de 95% de este resultado estar certo; não corrige casos enviesados.')}
 ${metricCard('Precisão',c?percent(c.precision):'—',`Quando o modelo disse <strong>“${esc(className(metricFilter.label)||'esta classe')}”</strong>, com que frequência acertou?`,c?`${c.tp} acertos entre ${c.tp+c.fp} vezes que escolheu essa classe. ${c.fp} falso(s) positivo(s).`:'Escolha uma classe com dados.','Verdadeiros positivos ÷ (verdadeiros positivos + falsos positivos). É útil quando um alarme indevido custa tempo. Se o modelo nunca escolheu a classe, a precisão fica indefinida, não zero.')}
 ${metricCard('Recall · capacidade de encontrar',c?percent(c.recall):'—',`Dos casos que realmente eram <strong>“${esc(className(metricFilter.label)||'esta classe')}”</strong>, quantos o modelo encontrou?`,c?`${c.tp} encontrados em ${c.tp+c.fn} casos reais da classe. ${c.fn} passou/passaram despercebido(s).`:'Escolha uma classe com dados.','Verdadeiros positivos ÷ (verdadeiros positivos + falsos negativos). É útil quando deixar passar um caso importante custa caro. Sem casos reais dessa classe, não há recall a estimar.')}
 ${metricCard('F1 da classe',c?percent(c.f1):'—','Resume o <strong>equilíbrio entre precisão e recall</strong> em um único número.',c?'Uma nota alta exige poucos alarmes falsos e poucas omissões ao mesmo tempo.':'Sem rótulos suficientes.','2 × precisão × recall ÷ (precisão + recall), quando a conta é definida. Aqui usamos a forma equivalente 2×acertos da classe ÷ (2×acertos + falsos positivos + falsos negativos). Não é o percentual total de acertos.')}
 ${metricCard('Macro-F1',percent(s.macroF1),'Calcula o F1 de cada classe e dá <strong>o mesmo peso a todas</strong>.',s.labels.length?`${s.labels.length} classes presentes no gabarito ou na predição. Uma classe comum não domina a média.`:'Sem classes para comparar.','Média simples dos F1 por classe presentes neste recorte. Ajuda a enxergar qualidade equilibrada. Não é comparável a outro recorte se a lista de classes mudar; classes ausentes precisam de coleta adicional.')}
 </div>
 ${s.labels.length?confusionSection(s):''}
 ${operationalSection(run,historical)}
 ${confidenceSection(rows)}
 <div class="panel"><div class="panel-head"><h2>Como decidir sem se enganar com um número</h2></div><div class="explain-list">
 <details open><summary>100% de acerto quer dizer que está resolvido?</summary><p>Não. Oito acertos em oito casos mostram que aqueles oito foram resolvidos. Com tão poucos exemplos, ainda há bastante incerteza sobre os próximos. Veja a faixa de confiança e teste casos novos de origens diferentes.</p></details>
 <details><summary>O que é um caso independente?</summary><p>É uma unidade que acrescenta informação nova. Fazer a mesma pergunta mil vezes testa repetibilidade, mas continua cobrindo essencialmente o mesmo problema. Paráfrases, a mesma conversa e decisões no mesmo lote podem estar relacionadas; a análise precisa levar isso em conta.</p></details>
 <details><summary>O que o p-valor permite concluir?</summary><p>Ele ajuda a avaliar se os dados são incompatíveis com uma hipótese de referência, seguindo um teste definido antes da análise. Não é a probabilidade de uma hipótese ser verdadeira. Não encontrar uma diferença também não demonstra equivalência: pode simplesmente haver poucos casos. Nos próximos testes, comparações pareadas e dependências entre casos precisam ser consideradas.</p></details>
 <details><summary>O que é não inferioridade?</summary><p>É perguntar se a opção mais barata ou rápida perde no máximo uma quantidade de qualidade que aceitamos antes do teste. Se aceitarmos até 5 pontos percentuais de perda, a comparação precisa ser precisa o suficiente para excluir perdas maiores. Só observar percentuais parecidos não basta.</p></details>
 <details><summary>O que são pontos percentuais?</summary><p>São a diferença direta entre percentuais. Passar de 80% para 85% é ganhar 5 pontos percentuais, embora o aumento relativo seja de 6,25%. O painel usa pontos percentuais para comparar taxas sem confundir essas duas coisas.</p></details>
 <details><summary>O que é cobertura e por que olhar erro junto com ela?</summary><p>Cobertura é a parcela dos casos que o sistema resolve sem encaminhar para revisão. Aceitar só os casos fáceis pode reduzir o erro, mas deixa mais trabalho para pessoas ou outro modelo. A escolha boa equilibra erro entre aceitos, casos encaminhados e custo total. Os pacotes atuais ainda não têm um campo de aceitação para calcular essa curva.</p></details>
 <details><summary>Como entender nDCG@5 nos testes de busca?</summary><p>É uma nota de ordenação: avalia se os resultados mais úteis aparecem nas primeiras cinco posições. Quanto mais perto de 1, melhor a ordem em relação ao gabarito. Não significa “percentual de respostas verdadeiras”. Ainda faltam rankings e relevâncias rotuladas no painel para calcular essa métrica.</p></details>
 </div></div>`;
}
function confusionSection(s){const total=s.labeled.length;
 return `<div class="panel"><div class="panel-head"><h2>Onde o modelo confundiu as classes</h2><span class="small muted">${total} decisões com dois rótulos</span></div><div class="panel-body"><p class="small muted">Leia por linha: ela mostra o gabarito. As colunas mostram o que o modelo respondeu. A diagonal representa acertos; os demais números são confusões.</p><div class="table-wrap"><table class="confusion"><thead><tr><th>Gabarito ↓ / resposta →</th>${s.labels.map(l=>`<th>${esc(className(l))}</th>`).join('')}</tr></thead><tbody>${s.labels.map(gold=>`<tr><th>${esc(className(gold))}</th>${s.labels.map(pred=>{const count=s.labeled.filter(r=>r.expected===gold&&r.predicted===pred).length;return `<td class="${gold===pred?'diagonal':count?'mistake':''}">${count}</td>`}).join('')}</tr>`).join('')}</tbody></table></div></div></div>`;
}
function operationalSection(run,historical){
 if(historical)return `<div class="panel"><div class="panel-head"><h2>Tempo e custo: o que temos do Hermes</h2><span class="badge">Valores reportados no PDF</span></div><div class="metric-grid compact">
 ${metricCard('Tempo mediano por chamada','284 ms / 263 ms','Individual / lote, no ensaio principal. <strong>Mediana</strong> é o tempo que fica no meio da lista ordenada.','Metade das chamadas ficou abaixo e metade acima, aproximadamente. Um lote continha oito decisões.','Valores reportados: 283,96 ms individual e 263,16 ms por lote. Não foram recalculados de timestamps originais, ainda não importados. São do ensaio inteiro, não do filtro de classificação acima.')}
 ${metricCard('Economia no custo de API','≈ 47%','Os lotes custaram menos para <strong>as mesmas 48 decisões</strong>.','Isso mede custo de API naquele ensaio. Não demonstra economia de tempo humano nem melhora da qualidade.','1 − (0,000496776 ÷ 0,000937272). Os dois valores em dólares vêm do relatório. Ordem e distrações também mudaram entre as condições.')}
 </div></div>`;
 const attempts=run?.attempts||[],success=attempts.filter(a=>a.status==='success'),finished=attempts.filter(a=>a.status!=='pending'),failed=finished.filter(a=>a.status==='error'||a.status==='timeout'),times=success.filter(a=>!a.cache_hit&&a.latency_ms!==null).map(a=>a.latency_ms),median=medianValue(times),p95=quantileNearest(times,.95),spent=attempts.reduce((n,a)=>n+(a.cost_usd||0),0),unknown=attempts.filter(a=>a.cost_usd===null).length;
 return `<div class="panel"><div class="panel-head"><h2>Operação da execução selecionada</h2><span class="small muted">Execução inteira, sem filtrar tarefa ou partição</span></div><div class="metric-grid compact">
 ${metricCard('Latência mediana · p50',median===null?'—':number(median)+' ms','Quanto demora uma tentativa típica? <strong>Mediana</strong> é o tempo no meio da lista.','Sucessos com duração informada e sem cache: '+times.length+'.','Ordenamos os tempos e pegamos o valor central; se há dois valores centrais, usamos a média. Falhas e respostas de cache ficam fora desta medida, mas aparecem nas contagens.')}
 ${metricCard('Latência p95',p95===null?'—':number(p95)+' ms','Um resumo das chamadas mais lentas: <strong>aproximadamente 95% dos tempos ficam até esse valor</strong>.',times.length<20?'Com menos de 20 tempos, esse número se aproxima do máximo e é instável. Use apenas como descrição.':`Calculado sobre ${times.length} sucessos sem cache. Falhas não somem: estão no indicador ao lado.`,'Percentil por posição: ordenamos os tempos e pegamos a posição arredondada para cima de 95% × N. Não é uma promessa de prazo das próximas chamadas.')}
 ${metricCard('Taxa de falha',finished.length?percent(failed.length/finished.length):'—','Quantas tentativas encerradas <strong>não entregaram uma resposta válida</strong>?',`${failed.length} falhas em ${finished.length} tentativas encerradas. ${attempts.length-finished.length} ainda pendentes.`,'Erros e timeouts ÷ tentativas encerradas. Um retry é outra tentativa; não apagamos a primeira falha. Falha técnica e resposta semanticamente errada são problemas diferentes.')}
 ${metricCard('Custo conhecido',run?money(spent):'—','Soma dos valores de API efetivamente <strong>informados nos registros</strong>.',unknown?`${unknown} tentativa(s) sem custo conhecido. Este valor pode aumentar após conciliação.`:'Inclui tentativas com custo registrado; não inclui tempo humano nem infraestrutura.','Somamos cost_usd. Campo null fica desconhecido e não é tratado como prova de gratuidade. Reservas pendentes são mostradas na área de orçamento.')}
 </div></div>`;
}
function confidenceSection(rows){const high=rows.filter(r=>r.confidence!==null&&r.confidence>=.9&&r.correct!==null),errors=high.filter(r=>!r.correct).length;
 return `<div class="panel"><div class="panel-head"><h2>Confiança do modelo não é certeza de acerto</h2></div><div class="panel-body"><p>O campo <span class="mono">confidence</span> descreve uma característica da resposta do modelo. Ele precisa ser testado na nossa tarefa antes de orientar decisões.</p><div class="confidence-callout"><strong>${high.length?errors+' / '+high.length:'Sem dados'}</strong><span>${high.length?'erros entre decisões avaliadas com confidence ≥ 0,90, no recorte atual.':'Neste recorte não há decisões avaliadas com confidence ≥ 0,90.'}</span></div><p class="small muted">Esse corte é apenas uma descrição fixa. Zero erros em poucos casos não valida o limiar. Uma análise de calibração exigirá dados adequados; não tratamos confidence como probabilidade comprovada de acerto.</p></div></div>`;
}
function bindMetrics(){
 document.querySelectorAll('[data-metric-source]').forEach(b=>b.onclick=()=>{metricFilter.source=b.dataset.metricSource;metricFilter.split=metricFilter.source==='history'?'holdout':'';if(metricFilter.source==='new')metricFilter.run=state.runs[0]?.id||'';render()});
 for(const [id,key] of Object.entries({metricFormat:'format',metricTask:'task',metricSplit:'split',metricLabel:'label',metricRun:'run'})){const element=$('#'+id);if(element)element.onchange=()=>{metricFilter[key]=element.value;render()}}
}
