let terminalFilter='all';
function plannedQueue(){return ['simple','deep'].flatMap(phase=>PLAN.systems.map(s=>{
 const runs=state.runs.filter(r=>r.system_id===s.id&&r.phase===phase).sort((a,b)=>Date.parse(b.started_at)-Date.parse(a.started_at));
 const latest=runs[0],status=latest?(latest.status==='completed'?'done':latest.status==='failed'?'blocked':'running'):progress(s.id,phase);
 return {system:s,phase,runs,latest,status};
}))}
function terminalLines(){
 const lines=state.events.map(e=>({at:e.at,type:e.kind==='manual'?'manual':'data',label:e.kind==='manual'?'NOTA':'DADOS',text:e.text}));
 for(const r of state.runs){lines.push({at:r.started_at,type:'run',label:'EXECUÇÃO',text:`${r.system_id} / ${PHASES[r.phase]} / ${r.id} — ${LABELS[r.status]}. ${r.attempts.length} tentativas; ${r.decisions.length} decisões. Evidência: ${EVIDENCE[r.evidence]}.`});
  if(r.finished_at)lines.push({at:r.finished_at,type:'run',label:'FIM',text:`${r.id} — ${LABELS[r.status]}. Custo conhecido: ${money(r.attempts.reduce((n,a)=>n+(a.cost_usd||0),0))}.`});
 }
 return lines.filter(l=>terminalFilter==='all'||l.type===terminalFilter).sort((a,b)=>Date.parse(b.at)-Date.parse(a.at)).slice(0,100);
}
function decisionBoard(){const d=state.decision;
 if(!d)return '';
 const cards=d.cartoes.map(c=>`<article class="decision-card ${c.estado==='pendente'?'pending':''}"><span class="eyebrow">${esc(c.titulo)}</span><strong>${esc(c.valor)}</strong><span class="decision-versus">${esc(c.comparacao)}</span><p>${esc(c.leitura)}</p><small class="muted">${esc(c.fonte)}</small></article>`).join('');
 const orc=d.orcamento?`<p class="small muted">Orçamento: ${money(d.orcamento.comprometido_nusd/1e9,6)} comprometidos · ${money(d.orcamento.disponivel_nusd/1e9,4)} disponíveis do teto autorizado.</p>`:'';
 return `<div class="panel decision-panel"><div class="panel-head"><h2>Placar de decisão</h2><span class="eyebrow">ATUALIZADO ${date(d.atualizado_em)}</span></div><div class="panel-body"><h3>${esc(d.veredito.titulo)}</h3><p class="muted">${esc(d.veredito.texto)}</p><p class="small muted">Confiança ${String(d.veredito.confianca).replace('.', ',')}: ${esc(d.veredito.confianca_nota)}</p>${d.veredito.confianca_motivos?`<details class="small muted"><summary>Como a confiança foi descontada</summary><ul>${d.veredito.confianca_motivos.map(m=>`<li>${esc(m)}</li>`).join('')}</ul></details>`:''}${orc}</div><div class="decision-grid">${cards}</div><div class="panel-body"><h3>O que ainda falta para decidir</h3><ul class="small muted">${d.pendencias.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div></div>`;
}
function terminalView(){const m=metrics(),queue=plannedQueue(),active=state.runs.filter(r=>r.status==='running'),concluded=state.runs.filter(r=>r.status!=='running'),verified=queue.filter(q=>q.latest?.status==='completed').length,lines=terminalLines(),next=queue.find(q=>!q.latest&&q.status!=='done'),step=STAGES.findIndex((s,i)=>i>0&&stageStatus(i)!=='done');
 return intro('TERMINAL / PRÓXIMOS EXPERIMENTOS','Execução do plano JEV.','Acompanhe os testes planejados, a atividade registrada e as evidências que cada rodada produzir.',`<button class="button" data-go="systems">Consultar protocolos ↗</button>`)+
 `<div class="terminal-status"><span class="terminal-signal ${active.length?'active':''}"></span><div><strong>${active.length?active.length+' execução(ões) em andamento':(concluded.length?concluded.length+' execução(ões) registrada(s), nenhuma em andamento':'Aguardando a primeira execução')}</strong><p>${active.length?active.map(r=>esc(r.id)).join(' · '):(concluded.length?'Execução registrada não é sistema aprovado. A evidência de cada uma está em Resultados.':'A fila está preparada. Resultados, métricas e custos serão preenchidos pelos novos testes.')}</p></div><span class="badge">${mode==='api'?'Acompanhamento conectado':'Acompanhamento local'}</span></div>
 `+decisionBoard()+`
 <div class="kpis"><div class="kpi"><div class="label">Rodadas planejadas</div><strong>30</strong><small>15 simples + 15 aprofundadas</small></div><div class="kpi"><div class="label">Concluídas com dados</div><strong>${verified}<span class="muted" style="font-size:18px"> / 30</span></strong><small>Execução concluída não significa aprovação</small></div><div class="kpi"><div class="label">Decisões dos novos testes</div><strong>${number(m.decisions.length)}</strong><small>${m.attempts.length} tentativas registradas</small></div><div class="kpi"><div class="label">Custo da nova etapa</div><strong>${money(m.spent,4)}</strong><small>${m.unknown?m.unknown+' custos ainda desconhecidos':'Custo conhecido das execuções registradas'}</small></div></div>
 <div class="console-panel"><div class="console-head"><div><span class="console-dot"></span> REGISTRO DE ATIVIDADE <span class="small">/ NOVA ETAPA</span></div><select id="terminalFilter" aria-label="Filtrar atividade">${opts({all:'Todos os registros',run:'Execuções',data:'Dados importados',manual:'Acompanhamento'},terminalFilter)}</select></div><div class="console-output" role="log" aria-label="Registros da nova etapa">${lines.length?lines.map(l=>`<div class="console-line"><time>${date(l.at)}</time><span class="console-label">${l.label}</span><span>${esc(l.text)}</span></div>`).join(''):'<div class="console-empty">Nenhum evento de execução recebido.<br><span>Os registros aparecerão aqui quando o executor publicar dados da nova etapa.</span></div>'}</div><div class="console-foot">${mode==='api'?'Atualização automática a cada 5 segundos':'Abra o modo conectado para acompanhar atualizações da pasta'} · Até 100 registros recentes</div></div>
 <div class="columns"><div><div class="panel"><div class="panel-head"><h2>Fila dos próximos testes</h2><button class="text-link" data-go="execution">Editar acompanhamento</button></div><div class="table-wrap"><table><thead><tr><th>Ordem</th><th>Sistema / rodada</th><th>Estado</th><th>Evidência</th></tr></thead><tbody>${queue.map((q,i)=>`<tr><td class="mono">${String(i+1).padStart(2,'0')}</td><td><button class="name-button" data-system="${q.system.id}">${esc(q.system.name)}</button><br><small>${PHASES[q.phase]}${q.phase==='simple'?' · '+q.system.smoke_units+' '+esc(q.system.smoke_unit):''}</small></td><td>${badge(q.status)}</td><td>${q.latest?`<button class="text-link" data-run="${esc(q.latest.id)}">${q.runs.length} execução(ões) ↗</button>`:`<span class="small muted">${q.status==='planned'?'Ainda sem execução':'Status manual; sem dados'}</span>`}</td></tr>`).join('')}</tbody></table></div></div></div>
 <div><div class="panel"><div class="panel-head"><h2>Próximo passo</h2><span class="eyebrow">PLANO</span></div><div class="panel-body"><h3>${step>0?esc(STAGES[step][0]):'Conferir conclusões e evidências'}</h3><p class="muted small">${step>0?esc(STAGES[step][1]):'Todas as etapas foram marcadas como concluídas no acompanhamento.'}</p>${next?`<div class="hint"><strong>Próximo protocolo pendente</strong><br>${esc(next.system.name)} · ${PHASES[next.phase]}<br><button class="text-link" data-system="${next.system.id}">Ver o que será testado</button></div>`:''}<p class="small muted">A ordem organiza o acompanhamento. Dependências e controles financeiros precisam estar prontos antes do despacho de chamadas.</p></div></div>
 <div class="panel"><div class="panel-head"><h2>Execução atual</h2></div>${active.length?`<div class="panel-body">${active.map(r=>`<h3>${esc(system(r.system_id).name)}</h3><p class="small muted">${esc(r.id)} · ${date(r.started_at)}</p><button class="button" data-run="${esc(r.id)}">Inspecionar registros</button>`).join('')}</div>`:empty('Nenhuma execução ativa registrada','Este terminal acompanha os registros do executor. Ele não inicia inferências nem presume que um teste esteja rodando.')}</div>
 <div class="panel"><div class="panel-head"><h2>Resultados da nova etapa</h2></div><div class="panel-body"><p class="muted small">Acurácia, precisão, recall, incerteza, latência e custo serão calculados a partir dos novos registros, com explicação junto de cada indicador.</p><button class="button dark" data-go="metrics">Ver métricas dos testes ↗</button></div></div></div></div>
`;
}
